// x/node errors (1100s)
export const ERR_INVALID_SIGNER = 1100;
export const ERR_NODE_NOT_FOUND = 1101;
export const ERR_NODE_ALREADY_EXISTS = 1102;
export const ERR_AGENT_ADDRESS_ALREADY_USED = 1103;
export const ERR_REGISTRATION_POOL_DEPLETED = 1104;
export const ERR_MAX_REGISTRATIONS_PER_BLOCK = 1105;
export const ERR_INVALID_AGENT_SHARE = 1106;
export const ERR_INVALID_TAGS = 1107;
export const ERR_UNAUTHORIZED_OPERATOR = 1108;
export const ERR_UNAUTHORIZED_AGENT_MSG = 1109;
export const ERR_AGENT_ADDRESS_CHANGE_COOLDOWN = 1110;
export const ERR_NODE_NOT_ACTIVE = 1111;
export const ERR_INVALID_CONSENSUS_PUBKEY = 1112;
export const ERR_AGENT_SHARE_CHANGE_EXCEEDS_MAX = 1113;
export const ERR_NODE_INACTIVE = 1116;
export const ERR_VALIDATOR_ALREADY_EXISTS = 1117;
export const ERR_AGENT_SHARE_CHANGE_PENDING = 1118;

// x/activity errors (1200s)
export const ERR_SUBMITTER_NOT_REGISTERED = 1200;
export const ERR_NODE_NOT_ELIGIBLE = 1201;
export const ERR_DUPLICATE_ACTIVITY_HASH = 1202;
export const ERR_QUOTA_EXCEEDED = 1203;
export const ERR_INVALID_ACTIVITY_HASH = 1204;
export const ERR_INVALID_CONTENT_URI = 1205;
export const ERR_INVALID_AUTHORITY = 1206;
export const ERR_INVALID_PARAMS = 1207;
export const ERR_ACTIVITY_NOT_FOUND = 1208;
export const ERR_NODE_NOT_FOUND_ACTIVITY = 1209;

// SDK errors (9000s)
export const ERR_NOT_CONNECTED = 9000;
export const ERR_BROADCAST_FAILED = 9001;
export const ERR_TX_TIMEOUT = 9002;
export const ERR_TX_NOT_FOUND = 9003;
export const ERR_SIGNING_FAILED = 9004;
export const ERR_INVALID_CONFIG = 9005;
export const ERR_QUERY_FAILED = 9006;
export const ERR_INVALID_ADDRESS = 9007;
