version: 1
validation: sovereign
default_denom: uppyeo
accounts:
- name: alice
  coins:
  - 20000token
  - 2000000000000uppyeo
- name: bob
  coins:
  - 10000token
  - 1000000000000uppyeo
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: bob
  coins:
  - 5token
  - 1000000000uppyeo
validators:
- name: alice
  bonded: 1000000000000uppyeo
- name: validator1
  bonded: 2000000000000uppyeo
- name: validator2
  bonded: 1000000000000uppyeo
