// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: seocheon/randomness/v1/params.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the x/randomness module.
type Params struct {
	// beacon_verification_enabled controls whether drand beacon signatures are verified on-chain.
	// Set to false initially to allow stub-mode operation.
	BeaconVerificationEnabled bool `protobuf:"varint,1,opt,name=beacon_verification_enabled,json=beaconVerificationEnabled,proto3" json:"beacon_verification_enabled,omitempty"`
	// max_beacon_age_blocks is the maximum age (in blocks) for a beacon to be accepted.
	// Beacons older than current_height - max_beacon_age_blocks are rejected.
	MaxBeaconAgeBlocks uint64 `protobuf:"varint,2,opt,name=max_beacon_age_blocks,json=maxBeaconAgeBlocks,proto3" json:"max_beacon_age_blocks,omitempty"`
	// drand_genesis_time is the drand network genesis time (Unix seconds).
	DrandGenesisTime uint64 `protobuf:"varint,3,opt,name=drand_genesis_time,json=drandGenesisTime,proto3" json:"drand_genesis_time,omitempty"`
	// drand_period_seconds is the drand beacon emission period in seconds.
	DrandPeriodSeconds uint64 `protobuf:"varint,4,opt,name=drand_period_seconds,json=drandPeriodSeconds,proto3" json:"drand_period_seconds,omitempty"`
	// drand_chain_hash is the drand chain hash for beacon verification.
	DrandChainHash string `protobuf:"bytes,5,opt,name=drand_chain_hash,json=drandChainHash,proto3" json:"drand_chain_hash,omitempty"`
	// drand_public_key is the drand quicknet G2 public key (hex-encoded).
	// Used for BLS12-381 signature verification when beacon_verification_enabled is true.
	DrandPublicKey string `protobuf:"bytes,6,opt,name=drand_public_key,json=drandPublicKey,proto3" json:"drand_public_key,omitempty"`
	// drand_scheme_id is the drand signature scheme identifier.
	// Default: "bls-unchained-g1-rfc9380" for quicknet.
	DrandSchemeId string `protobuf:"bytes,7,opt,name=drand_scheme_id,json=drandSchemeId,proto3" json:"drand_scheme_id,omitempty"`
	// commit_reveal_enabled controls whether the commit-reveal randomness request system is active.
	// When false, MsgRequestRandomness is rejected.
	CommitRevealEnabled bool `protobuf:"varint,8,opt,name=commit_reveal_enabled,json=commitRevealEnabled,proto3" json:"commit_reveal_enabled,omitempty"`
	// min_future_rounds is the minimum number of drand rounds into the future for target_round.
	// Ensures the beacon is not yet available at request time (front-run resistance).
	MinFutureRounds uint64 `protobuf:"varint,9,opt,name=min_future_rounds,json=minFutureRounds,proto3" json:"min_future_rounds,omitempty"`
	// request_timeout_blocks is the maximum number of blocks before a pending request expires.
	RequestTimeoutBlocks uint64 `protobuf:"varint,10,opt,name=request_timeout_blocks,json=requestTimeoutBlocks,proto3" json:"request_timeout_blocks,omitempty"`
	// request_pruning_blocks is the number of blocks after fulfillment/expiry before a request is pruned.
	RequestPruningBlocks uint64 `protobuf:"varint,11,opt,name=request_pruning_blocks,json=requestPruningBlocks,proto3" json:"request_pruning_blocks,omitempty"`
	// max_pending_requests is the global maximum number of pending randomness requests.
	MaxPendingRequests uint64 `protobuf:"varint,12,opt,name=max_pending_requests,json=maxPendingRequests,proto3" json:"max_pending_requests,omitempty"`
	// max_requests_per_requester is the maximum number of pending requests per requester address.
	MaxRequestsPerRequester uint64 `protobuf:"varint,13,opt,name=max_requests_per_requester,json=maxRequestsPerRequester,proto3" json:"max_requests_per_requester,omitempty"`
	// max_fulfills_per_block is the maximum number of requests fulfilled per EndBlocker invocation.
	MaxFulfillsPerBlock uint64 `protobuf:"varint,14,opt,name=max_fulfills_per_block,json=maxFulfillsPerBlock,proto3" json:"max_fulfills_per_block,omitempty"`
	// min_request_fee is the minimum fee required to submit a randomness request.
	// Escrowed by the module and paid to the relayer on fulfillment, or refunded on expiry.
	MinRequestFee types.Coin `protobuf:"bytes,15,opt,name=min_request_fee,json=minRequestFee,proto3" json:"min_request_fee"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b4903869b7070e, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBeaconVerificationEnabled() bool {
	if m != nil {
		return m.BeaconVerificationEnabled
	}
	return false
}

func (m *Params) GetMaxBeaconAgeBlocks() uint64 {
	if m != nil {
		return m.MaxBeaconAgeBlocks
	}
	return 0
}

func (m *Params) GetDrandGenesisTime() uint64 {
	if m != nil {
		return m.DrandGenesisTime
	}
	return 0
}

func (m *Params) GetDrandPeriodSeconds() uint64 {
	if m != nil {
		return m.DrandPeriodSeconds
	}
	return 0
}

func (m *Params) GetDrandChainHash() string {
	if m != nil {
		return m.DrandChainHash
	}
	return ""
}

func (m *Params) GetDrandPublicKey() string {
	if m != nil {
		return m.DrandPublicKey
	}
	return ""
}

func (m *Params) GetDrandSchemeId() string {
	if m != nil {
		return m.DrandSchemeId
	}
	return ""
}

func (m *Params) GetCommitRevealEnabled() bool {
	if m != nil {
		return m.CommitRevealEnabled
	}
	return false
}

func (m *Params) GetMinFutureRounds() uint64 {
	if m != nil {
		return m.MinFutureRounds
	}
	return 0
}

func (m *Params) GetRequestTimeoutBlocks() uint64 {
	if m != nil {
		return m.RequestTimeoutBlocks
	}
	return 0
}

func (m *Params) GetRequestPruningBlocks() uint64 {
	if m != nil {
		return m.RequestPruningBlocks
	}
	return 0
}

func (m *Params) GetMaxPendingRequests() uint64 {
	if m != nil {
		return m.MaxPendingRequests
	}
	return 0
}

func (m *Params) GetMaxRequestsPerRequester() uint64 {
	if m != nil {
		return m.MaxRequestsPerRequester
	}
	return 0
}

func (m *Params) GetMaxFulfillsPerBlock() uint64 {
	if m != nil {
		return m.MaxFulfillsPerBlock
	}
	return 0
}

func (m *Params) GetMinRequestFee() types.Coin {
	if m != nil {
		return m.MinRequestFee
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*Params)(nil), "seocheon.randomness.v1.Params")
}

func init() {
	proto.RegisterFile("seocheon/randomness/v1/params.proto", fileDescriptor_01b4903869b7070e)
}

var fileDescriptor_01b4903869b7070e = []byte{
	// 619 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xcf, 0x6e, 0xd3, 0x4a,
	0x18, 0xc5, 0xe3, 0x7b, 0x7b, 0x73, 0xdb, 0xe9, 0x6d, 0x7b, 0x3b, 0x4d, 0x8b, 0xdb, 0x22, 0x37,
	0x02, 0x81, 0xa2, 0x0a, 0xd9, 0x4d, 0x0b, 0x1b, 0x90, 0x90, 0x48, 0x45, 0x0b, 0x62, 0x63, 0xb9,
	0x15, 0x0b, 0x36, 0xa3, 0xb1, 0xfd, 0x25, 0x19, 0xd5, 0x33, 0x63, 0x66, 0xec, 0x28, 0x7d, 0x05,
	0x56, 0x3c, 0x02, 0x8f, 0xc0, 0x8e, 0x57, 0xe8, 0xb2, 0x4b, 0x56, 0x08, 0xb5, 0x0b, 0x78, 0x0c,
	0xe4, 0x19, 0xbb, 0x0d, 0x12, 0x9b, 0xc8, 0x39, 0xbf, 0x73, 0xe6, 0xcf, 0x37, 0x3a, 0xe8, 0xbe,
	0x06, 0x99, 0x8c, 0x41, 0x8a, 0x40, 0x51, 0x91, 0x4a, 0x2e, 0x40, 0xeb, 0x60, 0xd2, 0x0f, 0x72,
	0xaa, 0x28, 0xd7, 0x7e, 0xae, 0x64, 0x21, 0xf1, 0x46, 0x63, 0xf2, 0x6f, 0x4d, 0xfe, 0xa4, 0xbf,
	0xb5, 0x4a, 0x39, 0x13, 0x32, 0x30, 0xbf, 0xd6, 0xba, 0xe5, 0x25, 0x52, 0x73, 0xa9, 0x83, 0x98,
	0x6a, 0x08, 0x26, 0xfd, 0x18, 0x0a, 0xda, 0x0f, 0x12, 0xc9, 0x44, 0xcd, 0x3b, 0x23, 0x39, 0x92,
	0xe6, 0x33, 0xa8, 0xbe, 0xac, 0x7a, 0xef, 0x4b, 0x1b, 0xb5, 0x43, 0xb3, 0x23, 0x7e, 0x8e, 0xb6,
	0x63, 0xa0, 0x89, 0x14, 0x64, 0x02, 0x8a, 0x0d, 0x59, 0x42, 0x0b, 0x26, 0x05, 0x01, 0x41, 0xe3,
	0x0c, 0x52, 0xd7, 0xe9, 0x3a, 0xbd, 0xf9, 0x68, 0xd3, 0x5a, 0xde, 0xce, 0x38, 0x5e, 0x5a, 0x03,
	0xee, 0xa3, 0x75, 0x4e, 0xa7, 0xa4, 0x5e, 0x83, 0x8e, 0x80, 0xc4, 0x99, 0x4c, 0xce, 0xb4, 0xfb,
	0x57, 0xd7, 0xe9, 0xcd, 0x45, 0x98, 0xd3, 0xe9, 0xc0, 0xb0, 0x17, 0x23, 0x18, 0x18, 0x82, 0x1f,
	0x21, 0x9c, 0x56, 0x17, 0x23, 0x23, 0x10, 0xa0, 0x99, 0x26, 0x05, 0xe3, 0xe0, 0xfe, 0x6d, 0xfc,
	0xff, 0x1b, 0x72, 0x6c, 0xc1, 0x29, 0xe3, 0x80, 0xf7, 0x50, 0xc7, 0xba, 0x73, 0x50, 0x4c, 0xa6,
	0x44, 0x43, 0x22, 0x45, 0xaa, 0xdd, 0x39, 0xbb, 0xbe, 0x61, 0xa1, 0x41, 0x27, 0x96, 0xe0, 0x1e,
	0xb2, 0xab, 0x90, 0x64, 0x4c, 0x99, 0x20, 0x63, 0xaa, 0xc7, 0xee, 0x3f, 0x5d, 0xa7, 0xb7, 0x10,
	0x2d, 0x1b, 0xfd, 0xb0, 0x92, 0x5f, 0x51, 0x3d, 0xbe, 0x75, 0xe6, 0x65, 0x9c, 0xb1, 0x84, 0x9c,
	0xc1, 0xb9, 0xdb, 0x9e, 0x71, 0x86, 0x46, 0x7e, 0x03, 0xe7, 0xf8, 0x21, 0x5a, 0xb1, 0x4e, 0x9d,
	0x8c, 0x81, 0x03, 0x61, 0xa9, 0xfb, 0xaf, 0x31, 0x2e, 0x19, 0xf9, 0xc4, 0xa8, 0xaf, 0x53, 0xbc,
	0x8f, 0xd6, 0x13, 0xc9, 0x39, 0x2b, 0x88, 0x82, 0x09, 0xd0, 0xec, 0x66, 0x90, 0xf3, 0x66, 0x90,
	0x6b, 0x16, 0x46, 0x86, 0x35, 0x23, 0xdc, 0x45, 0xab, 0x9c, 0x09, 0x32, 0x2c, 0x8b, 0x52, 0x01,
	0x51, 0xb2, 0xac, 0xae, 0xb7, 0x60, 0xae, 0xb7, 0xc2, 0x99, 0x38, 0x32, 0x7a, 0x64, 0x64, 0xfc,
	0x18, 0x6d, 0x28, 0x78, 0x5f, 0x82, 0x2e, 0xcc, 0xd4, 0x64, 0x59, 0x34, 0xf3, 0x46, 0x26, 0xd0,
	0xa9, 0xe9, 0xa9, 0x85, 0xf5, 0xc4, 0x67, 0x52, 0xb9, 0x2a, 0x05, 0x13, 0xa3, 0x26, 0xb5, 0xf8,
	0x5b, 0x2a, 0xb4, 0xb0, 0x4e, 0xed, 0xa1, 0x4e, 0xf5, 0xb4, 0x39, 0x88, 0xb4, 0x4a, 0xd4, 0x1e,
	0xed, 0xfe, 0x77, 0xf3, 0xb2, 0xa1, 0x45, 0x51, 0x4d, 0xf0, 0x33, 0xb4, 0x55, 0x25, 0x1a, 0x67,
	0xf5, 0x64, 0xcd, 0x1f, 0x50, 0xee, 0x92, 0xc9, 0xdd, 0xe1, 0x74, 0xda, 0x04, 0x42, 0x50, 0x51,
	0x83, 0xf1, 0x01, 0xda, 0xa8, 0xc2, 0xc3, 0x32, 0x1b, 0xb2, 0x2c, 0xb3, 0x61, 0x73, 0x4a, 0x77,
	0xd9, 0x04, 0xd7, 0x38, 0x9d, 0x1e, 0xd5, 0x30, 0x04, 0x65, 0x0e, 0x89, 0x8f, 0x51, 0x35, 0xa2,
	0x66, 0x13, 0x32, 0x04, 0x70, 0x57, 0xba, 0x4e, 0x6f, 0x71, 0x7f, 0xd3, 0xb7, 0xcd, 0xf0, 0xab,
	0x66, 0xf8, 0x75, 0x33, 0xfc, 0x43, 0xc9, 0xc4, 0x60, 0xee, 0xe2, 0xdb, 0x4e, 0x2b, 0x5a, 0xe2,
	0x4c, 0xd4, 0x9b, 0x1f, 0x01, 0x3c, 0x7d, 0xf0, 0xf3, 0xd3, 0x8e, 0xf3, 0xe1, 0xc7, 0xe7, 0xdd,
	0xbb, 0x37, 0x0d, 0x9d, 0xce, 0x76, 0xd4, 0xd6, 0x65, 0xf0, 0xe4, 0xe2, 0xca, 0x73, 0x2e, 0xaf,
	0x3c, 0xe7, 0xfb, 0x95, 0xe7, 0x7c, 0xbc, 0xf6, 0x5a, 0x97, 0xd7, 0x5e, 0xeb, 0xeb, 0xb5, 0xd7,
	0x7a, 0xb7, 0xfd, 0xe7, 0x5c, 0x71, 0x9e, 0x83, 0x8e, 0xdb, 0xa6, 0x77, 0x07, 0xbf, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x64, 0xf3, 0xb1, 0x56, 0xff, 0x03, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.BeaconVerificationEnabled != that1.BeaconVerificationEnabled {
		return false
	}
	if this.MaxBeaconAgeBlocks != that1.MaxBeaconAgeBlocks {
		return false
	}
	if this.DrandGenesisTime != that1.DrandGenesisTime {
		return false
	}
	if this.DrandPeriodSeconds != that1.DrandPeriodSeconds {
		return false
	}
	if this.DrandChainHash != that1.DrandChainHash {
		return false
	}
	if this.DrandPublicKey != that1.DrandPublicKey {
		return false
	}
	if this.DrandSchemeId != that1.DrandSchemeId {
		return false
	}
	if this.CommitRevealEnabled != that1.CommitRevealEnabled {
		return false
	}
	if this.MinFutureRounds != that1.MinFutureRounds {
		return false
	}
	if this.RequestTimeoutBlocks != that1.RequestTimeoutBlocks {
		return false
	}
	if this.RequestPruningBlocks != that1.RequestPruningBlocks {
		return false
	}
	if this.MaxPendingRequests != that1.MaxPendingRequests {
		return false
	}
	if this.MaxRequestsPerRequester != that1.MaxRequestsPerRequester {
		return false
	}
	if this.MaxFulfillsPerBlock != that1.MaxFulfillsPerBlock {
		return false
	}
	if !this.MinRequestFee.Equal(&that1.MinRequestFee) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MinRequestFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x7a
	if m.MaxFulfillsPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxFulfillsPerBlock))
		i--
		dAtA[i] = 0x70
	}
	if m.MaxRequestsPerRequester != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxRequestsPerRequester))
		i--
		dAtA[i] = 0x68
	}
	if m.MaxPendingRequests != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPendingRequests))
		i--
		dAtA[i] = 0x60
	}
	if m.RequestPruningBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RequestPruningBlocks))
		i--
		dAtA[i] = 0x58
	}
	if m.RequestTimeoutBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RequestTimeoutBlocks))
		i--
		dAtA[i] = 0x50
	}
	if m.MinFutureRounds != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinFutureRounds))
		i--
		dAtA[i] = 0x48
	}
	if m.CommitRevealEnabled {
		i--
		if m.CommitRevealEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if len(m.DrandSchemeId) > 0 {
		i -= len(m.DrandSchemeId)
		copy(dAtA[i:], m.DrandSchemeId)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DrandSchemeId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.DrandPublicKey) > 0 {
		i -= len(m.DrandPublicKey)
		copy(dAtA[i:], m.DrandPublicKey)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DrandPublicKey)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DrandChainHash) > 0 {
		i -= len(m.DrandChainHash)
		copy(dAtA[i:], m.DrandChainHash)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DrandChainHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.DrandPeriodSeconds != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DrandPeriodSeconds))
		i--
		dAtA[i] = 0x20
	}
	if m.DrandGenesisTime != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DrandGenesisTime))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxBeaconAgeBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxBeaconAgeBlocks))
		i--
		dAtA[i] = 0x10
	}
	if m.BeaconVerificationEnabled {
		i--
		if m.BeaconVerificationEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BeaconVerificationEnabled {
		n += 2
	}
	if m.MaxBeaconAgeBlocks != 0 {
		n += 1 + sovParams(uint64(m.MaxBeaconAgeBlocks))
	}
	if m.DrandGenesisTime != 0 {
		n += 1 + sovParams(uint64(m.DrandGenesisTime))
	}
	if m.DrandPeriodSeconds != 0 {
		n += 1 + sovParams(uint64(m.DrandPeriodSeconds))
	}
	l = len(m.DrandChainHash)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.DrandPublicKey)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.DrandSchemeId)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.CommitRevealEnabled {
		n += 2
	}
	if m.MinFutureRounds != 0 {
		n += 1 + sovParams(uint64(m.MinFutureRounds))
	}
	if m.RequestTimeoutBlocks != 0 {
		n += 1 + sovParams(uint64(m.RequestTimeoutBlocks))
	}
	if m.RequestPruningBlocks != 0 {
		n += 1 + sovParams(uint64(m.RequestPruningBlocks))
	}
	if m.MaxPendingRequests != 0 {
		n += 1 + sovParams(uint64(m.MaxPendingRequests))
	}
	if m.MaxRequestsPerRequester != 0 {
		n += 1 + sovParams(uint64(m.MaxRequestsPerRequester))
	}
	if m.MaxFulfillsPerBlock != 0 {
		n += 1 + sovParams(uint64(m.MaxFulfillsPerBlock))
	}
	l = m.MinRequestFee.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconVerificationEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BeaconVerificationEnabled = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBeaconAgeBlocks", wireType)
			}
			m.MaxBeaconAgeBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxBeaconAgeBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DrandGenesisTime", wireType)
			}
			m.DrandGenesisTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DrandGenesisTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DrandPeriodSeconds", wireType)
			}
			m.DrandPeriodSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DrandPeriodSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DrandChainHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DrandChainHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DrandPublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DrandPublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DrandSchemeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DrandSchemeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitRevealEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CommitRevealEnabled = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinFutureRounds", wireType)
			}
			m.MinFutureRounds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinFutureRounds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestTimeoutBlocks", wireType)
			}
			m.RequestTimeoutBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestTimeoutBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestPruningBlocks", wireType)
			}
			m.RequestPruningBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestPruningBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPendingRequests", wireType)
			}
			m.MaxPendingRequests = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPendingRequests |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRequestsPerRequester", wireType)
			}
			m.MaxRequestsPerRequester = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRequestsPerRequester |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxFulfillsPerBlock", wireType)
			}
			m.MaxFulfillsPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxFulfillsPerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinRequestFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinRequestFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
