// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: seocheon/randomness/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a10b92d105b2c3a, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a10b92d105b2c3a, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryLatestBeaconRequest is the request type for the Query/LatestBeacon RPC method.
type QueryLatestBeaconRequest struct {
}

func (m *QueryLatestBeaconRequest) Reset()         { *m = QueryLatestBeaconRequest{} }
func (m *QueryLatestBeaconRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLatestBeaconRequest) ProtoMessage()    {}
func (*QueryLatestBeaconRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a10b92d105b2c3a, []int{2}
}
func (m *QueryLatestBeaconRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLatestBeaconRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLatestBeaconRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLatestBeaconRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLatestBeaconRequest.Merge(m, src)
}
func (m *QueryLatestBeaconRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLatestBeaconRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLatestBeaconRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLatestBeaconRequest proto.InternalMessageInfo

// QueryLatestBeaconResponse is the response type for the Query/LatestBeacon RPC method.
type QueryLatestBeaconResponse struct {
	Beacon Beacon `protobuf:"bytes,1,opt,name=beacon,proto3" json:"beacon"`
}

func (m *QueryLatestBeaconResponse) Reset()         { *m = QueryLatestBeaconResponse{} }
func (m *QueryLatestBeaconResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLatestBeaconResponse) ProtoMessage()    {}
func (*QueryLatestBeaconResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a10b92d105b2c3a, []int{3}
}
func (m *QueryLatestBeaconResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLatestBeaconResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLatestBeaconResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLatestBeaconResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLatestBeaconResponse.Merge(m, src)
}
func (m *QueryLatestBeaconResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLatestBeaconResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLatestBeaconResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLatestBeaconResponse proto.InternalMessageInfo

func (m *QueryLatestBeaconResponse) GetBeacon() Beacon {
	if m != nil {
		return m.Beacon
	}
	return Beacon{}
}

// QueryBeaconRequest is the request type for the Query/Beacon RPC method.
type QueryBeaconRequest struct {
	Round uint64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
}

func (m *QueryBeaconRequest) Reset()         { *m = QueryBeaconRequest{} }
func (m *QueryBeaconRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBeaconRequest) ProtoMessage()    {}
func (*QueryBeaconRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a10b92d105b2c3a, []int{4}
}
func (m *QueryBeaconRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBeaconRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBeaconRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBeaconRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBeaconRequest.Merge(m, src)
}
func (m *QueryBeaconRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBeaconRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBeaconRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBeaconRequest proto.InternalMessageInfo

func (m *QueryBeaconRequest) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

// QueryBeaconResponse is the response type for the Query/Beacon RPC method.
type QueryBeaconResponse struct {
	Beacon Beacon `protobuf:"bytes,1,opt,name=beacon,proto3" json:"beacon"`
}

func (m *QueryBeaconResponse) Reset()         { *m = QueryBeaconResponse{} }
func (m *QueryBeaconResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBeaconResponse) ProtoMessage()    {}
func (*QueryBeaconResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a10b92d105b2c3a, []int{5}
}
func (m *QueryBeaconResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBeaconResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBeaconResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBeaconResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBeaconResponse.Merge(m, src)
}
func (m *QueryBeaconResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBeaconResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBeaconResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBeaconResponse proto.InternalMessageInfo

func (m *QueryBeaconResponse) GetBeacon() Beacon {
	if m != nil {
		return m.Beacon
	}
	return Beacon{}
}

// QueryBeaconsRequest is the request type for the Query/Beacons RPC method.
type QueryBeaconsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryBeaconsRequest) Reset()         { *m = QueryBeaconsRequest{} }
func (m *QueryBeaconsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBeaconsRequest) ProtoMessage()    {}
func (*QueryBeaconsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a10b92d105b2c3a, []int{6}
}
func (m *QueryBeaconsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBeaconsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBeaconsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBeaconsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBeaconsRequest.Merge(m, src)
}
func (m *QueryBeaconsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBeaconsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBeaconsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBeaconsRequest proto.InternalMessageInfo

func (m *QueryBeaconsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryBeaconsResponse is the response type for the Query/Beacons RPC method.
type QueryBeaconsResponse struct {
	Beacons    []Beacon            `protobuf:"bytes,1,rep,name=beacons,proto3" json:"beacons"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryBeaconsResponse) Reset()         { *m = QueryBeaconsResponse{} }
func (m *QueryBeaconsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBeaconsResponse) ProtoMessage()    {}
func (*QueryBeaconsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a10b92d105b2c3a, []int{7}
}
func (m *QueryBeaconsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBeaconsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBeaconsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBeaconsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBeaconsResponse.Merge(m, src)
}
func (m *QueryBeaconsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBeaconsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBeaconsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBeaconsResponse proto.InternalMessageInfo

func (m *QueryBeaconsResponse) GetBeacons() []Beacon {
	if m != nil {
		return m.Beacons
	}
	return nil
}

func (m *QueryBeaconsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryRandomnessRequestRequest is the request type for the Query/RandomnessRequest RPC method.
type QueryRandomnessRequestRequest struct {
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *QueryRandomnessRequestRequest) Reset()         { *m = QueryRandomnessRequestRequest{} }
func (m *QueryRandomnessRequestRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRandomnessRequestRequest) ProtoMessage()    {}
func (*QueryRandomnessRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a10b92d105b2c3a, []int{8}
}
func (m *QueryRandomnessRequestRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRandomnessRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRandomnessRequestRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRandomnessRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRandomnessRequestRequest.Merge(m, src)
}
func (m *QueryRandomnessRequestRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRandomnessRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRandomnessRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRandomnessRequestRequest proto.InternalMessageInfo

func (m *QueryRandomnessRequestRequest) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

// QueryRandomnessRequestResponse is the response type for the Query/RandomnessRequest RPC method.
type QueryRandomnessRequestResponse struct {
	Request RandomnessRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request"`
}

func (m *QueryRandomnessRequestResponse) Reset()         { *m = QueryRandomnessRequestResponse{} }
func (m *QueryRandomnessRequestResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRandomnessRequestResponse) ProtoMessage()    {}
func (*QueryRandomnessRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a10b92d105b2c3a, []int{9}
}
func (m *QueryRandomnessRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRandomnessRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRandomnessRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRandomnessRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRandomnessRequestResponse.Merge(m, src)
}
func (m *QueryRandomnessRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRandomnessRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRandomnessRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRandomnessRequestResponse proto.InternalMessageInfo

func (m *QueryRandomnessRequestResponse) GetRequest() RandomnessRequest {
	if m != nil {
		return m.Request
	}
	return RandomnessRequest{}
}

// QueryPendingRequestsRequest is the request type for the Query/PendingRequests RPC method.
type QueryPendingRequestsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryPendingRequestsRequest) Reset()         { *m = QueryPendingRequestsRequest{} }
func (m *QueryPendingRequestsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPendingRequestsRequest) ProtoMessage()    {}
func (*QueryPendingRequestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a10b92d105b2c3a, []int{10}
}
func (m *QueryPendingRequestsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingRequestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingRequestsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingRequestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingRequestsRequest.Merge(m, src)
}
func (m *QueryPendingRequestsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingRequestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingRequestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingRequestsRequest proto.InternalMessageInfo

func (m *QueryPendingRequestsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryPendingRequestsResponse is the response type for the Query/PendingRequests RPC method.
type QueryPendingRequestsResponse struct {
	Requests   []RandomnessRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryPendingRequestsResponse) Reset()         { *m = QueryPendingRequestsResponse{} }
func (m *QueryPendingRequestsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPendingRequestsResponse) ProtoMessage()    {}
func (*QueryPendingRequestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a10b92d105b2c3a, []int{11}
}
func (m *QueryPendingRequestsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingRequestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingRequestsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingRequestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingRequestsResponse.Merge(m, src)
}
func (m *QueryPendingRequestsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingRequestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingRequestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingRequestsResponse proto.InternalMessageInfo

func (m *QueryPendingRequestsResponse) GetRequests() []RandomnessRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *QueryPendingRequestsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryRequestsByRequesterRequest is the request type for the Query/RequestsByRequester RPC method.
type QueryRequestsByRequesterRequest struct {
	Requester  string             `protobuf:"bytes,1,opt,name=requester,proto3" json:"requester,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRequestsByRequesterRequest) Reset()         { *m = QueryRequestsByRequesterRequest{} }
func (m *QueryRequestsByRequesterRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequestsByRequesterRequest) ProtoMessage()    {}
func (*QueryRequestsByRequesterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a10b92d105b2c3a, []int{12}
}
func (m *QueryRequestsByRequesterRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRequestsByRequesterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRequestsByRequesterRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRequestsByRequesterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequestsByRequesterRequest.Merge(m, src)
}
func (m *QueryRequestsByRequesterRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRequestsByRequesterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequestsByRequesterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequestsByRequesterRequest proto.InternalMessageInfo

func (m *QueryRequestsByRequesterRequest) GetRequester() string {
	if m != nil {
		return m.Requester
	}
	return ""
}

func (m *QueryRequestsByRequesterRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryRequestsByRequesterResponse is the response type for the Query/RequestsByRequester RPC method.
type QueryRequestsByRequesterResponse struct {
	Requests   []RandomnessRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRequestsByRequesterResponse) Reset()         { *m = QueryRequestsByRequesterResponse{} }
func (m *QueryRequestsByRequesterResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRequestsByRequesterResponse) ProtoMessage()    {}
func (*QueryRequestsByRequesterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a10b92d105b2c3a, []int{13}
}
func (m *QueryRequestsByRequesterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRequestsByRequesterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRequestsByRequesterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRequestsByRequesterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequestsByRequesterResponse.Merge(m, src)
}
func (m *QueryRequestsByRequesterResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRequestsByRequesterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequestsByRequesterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequestsByRequesterResponse proto.InternalMessageInfo

func (m *QueryRequestsByRequesterResponse) GetRequests() []RandomnessRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *QueryRequestsByRequesterResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "seocheon.randomness.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "seocheon.randomness.v1.QueryParamsResponse")
	proto.RegisterType((*QueryLatestBeaconRequest)(nil), "seocheon.randomness.v1.QueryLatestBeaconRequest")
	proto.RegisterType((*QueryLatestBeaconResponse)(nil), "seocheon.randomness.v1.QueryLatestBeaconResponse")
	proto.RegisterType((*QueryBeaconRequest)(nil), "seocheon.randomness.v1.QueryBeaconRequest")
	proto.RegisterType((*QueryBeaconResponse)(nil), "seocheon.randomness.v1.QueryBeaconResponse")
	proto.RegisterType((*QueryBeaconsRequest)(nil), "seocheon.randomness.v1.QueryBeaconsRequest")
	proto.RegisterType((*QueryBeaconsResponse)(nil), "seocheon.randomness.v1.QueryBeaconsResponse")
	proto.RegisterType((*QueryRandomnessRequestRequest)(nil), "seocheon.randomness.v1.QueryRandomnessRequestRequest")
	proto.RegisterType((*QueryRandomnessRequestResponse)(nil), "seocheon.randomness.v1.QueryRandomnessRequestResponse")
	proto.RegisterType((*QueryPendingRequestsRequest)(nil), "seocheon.randomness.v1.QueryPendingRequestsRequest")
	proto.RegisterType((*QueryPendingRequestsResponse)(nil), "seocheon.randomness.v1.QueryPendingRequestsResponse")
	proto.RegisterType((*QueryRequestsByRequesterRequest)(nil), "seocheon.randomness.v1.QueryRequestsByRequesterRequest")
	proto.RegisterType((*QueryRequestsByRequesterResponse)(nil), "seocheon.randomness.v1.QueryRequestsByRequesterResponse")
}

func init() {
	proto.RegisterFile("seocheon/randomness/v1/query.proto", fileDescriptor_3a10b92d105b2c3a)
}

var fileDescriptor_3a10b92d105b2c3a = []byte{
	// 788 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x96, 0x4d, 0x4f, 0x13, 0x5d,
	0x14, 0xc7, 0x7b, 0x79, 0xa0, 0x3c, 0x3d, 0x9a, 0x18, 0x2e, 0x8d, 0xc1, 0x01, 0x06, 0x1c, 0x13,
	0x0a, 0x45, 0xe7, 0x52, 0x10, 0x5f, 0xa2, 0x21, 0xa1, 0x0b, 0x0d, 0xd1, 0x05, 0xd6, 0x8d, 0x9a,
	0x18, 0x32, 0xa5, 0x37, 0x63, 0x23, 0x9d, 0x3b, 0xcc, 0x0c, 0x44, 0x42, 0xd8, 0xb8, 0x31, 0x2e,
	0x4c, 0x8c, 0xae, 0x5c, 0xb9, 0x70, 0xe3, 0xca, 0xb8, 0x70, 0xa1, 0xdf, 0x80, 0xc4, 0x0d, 0x89,
	0x1b, 0x57, 0xc6, 0x80, 0x89, 0x5f, 0xc3, 0xf4, 0xde, 0x33, 0x6d, 0x07, 0x3a, 0x7d, 0x31, 0x2c,
	0xdc, 0x34, 0xb7, 0x77, 0xce, 0xff, 0x9c, 0xdf, 0x79, 0xe9, 0x99, 0x82, 0xe1, 0x73, 0xb1, 0xfa,
	0x88, 0x0b, 0x87, 0x79, 0x96, 0x53, 0x12, 0x15, 0x87, 0xfb, 0x3e, 0xdb, 0xcc, 0xb1, 0xf5, 0x0d,
	0xee, 0x6d, 0x99, 0xae, 0x27, 0x02, 0x41, 0x4f, 0x87, 0x36, 0x66, 0xdd, 0xc6, 0xdc, 0xcc, 0x69,
	0x03, 0x56, 0xa5, 0xec, 0x08, 0x26, 0x3f, 0x95, 0xa9, 0x96, 0x5d, 0x15, 0x7e, 0x45, 0xf8, 0xac,
	0x68, 0xf9, 0x5c, 0xf9, 0x60, 0x9b, 0xb9, 0x22, 0x0f, 0xac, 0x1c, 0x73, 0x2d, 0xbb, 0xec, 0x58,
	0x41, 0x59, 0x38, 0x68, 0x9b, 0xb6, 0x85, 0x2d, 0xe4, 0x91, 0x55, 0x4f, 0x78, 0x3b, 0x62, 0x0b,
	0x61, 0xaf, 0x71, 0x66, 0xb9, 0x65, 0x66, 0x39, 0x8e, 0x08, 0xa4, 0xc4, 0xc7, 0xa7, 0x99, 0x18,
	0xdc, 0x06, 0x30, 0x65, 0x78, 0x2e, 0xc6, 0xd0, 0xb5, 0x3c, 0xab, 0x82, 0x46, 0x46, 0x1a, 0xe8,
	0x9d, 0x2a, 0xe3, 0xb2, 0xbc, 0x2c, 0xf0, 0xf5, 0x0d, 0xee, 0x07, 0xc6, 0x3d, 0x18, 0x8c, 0xdc,
	0xfa, 0xae, 0x70, 0x7c, 0x4e, 0x17, 0x21, 0xa9, 0xc4, 0x43, 0x64, 0x9c, 0x4c, 0x9e, 0x98, 0xd5,
	0xcd, 0xe6, 0x65, 0x31, 0x95, 0x2e, 0x9f, 0xda, 0xfd, 0x31, 0x96, 0x78, 0xff, 0xfb, 0x63, 0x96,
	0x14, 0x50, 0x68, 0x68, 0x30, 0x24, 0x3d, 0xdf, 0xb6, 0x02, 0xee, 0x07, 0x79, 0x6e, 0xad, 0x0a,
	0x27, 0x8c, 0x7a, 0x1f, 0xce, 0x34, 0x79, 0x86, 0xb1, 0xaf, 0x43, 0xb2, 0x28, 0x6f, 0xda, 0xc5,
	0x56, 0xba, 0x7c, 0x6f, 0x35, 0x76, 0x01, 0x35, 0x46, 0x16, 0xd3, 0x8c, 0x04, 0xa4, 0x69, 0xe8,
	0xf3, 0xc4, 0x86, 0x53, 0x92, 0x2e, 0x7b, 0x0b, 0xea, 0x8b, 0x71, 0x17, 0x93, 0x3f, 0x56, 0x80,
	0x87, 0x11, 0xa7, 0x61, 0xa1, 0xe9, 0x0d, 0x80, 0xfa, 0x50, 0xa0, 0xe3, 0x09, 0x53, 0x4d, 0x90,
	0x59, 0x9d, 0x20, 0x53, 0x4d, 0x21, 0x4e, 0x90, 0xb9, 0x6c, 0xd9, 0x1c, 0xb5, 0x85, 0x06, 0xa5,
	0xf1, 0x96, 0x40, 0x3a, 0xea, 0x1f, 0xa9, 0x17, 0xa0, 0x5f, 0x11, 0x54, 0x7b, 0xf6, 0x5f, 0xc7,
	0xd8, 0xa1, 0x88, 0xde, 0x8c, 0x00, 0xf6, 0x48, 0xc0, 0x4c, 0x5b, 0x40, 0x15, 0x3c, 0x42, 0xb8,
	0x00, 0xa3, 0x12, 0xb0, 0x50, 0x0b, 0x1a, 0xe6, 0x81, 0xa5, 0x18, 0x05, 0xf0, 0xd4, 0x71, 0xa5,
	0x1c, 0x76, 0x24, 0x85, 0x37, 0x4b, 0x25, 0xe3, 0x31, 0xe8, 0x71, 0x7a, 0x4c, 0x75, 0x09, 0xfa,
	0xd1, 0x1c, 0x0b, 0x39, 0x15, 0x97, 0xea, 0x11, 0x1f, 0x61, 0xd6, 0xa8, 0x37, 0x38, 0x0c, 0xab,
	0xf9, 0xe7, 0x4e, 0xa9, 0xec, 0xd8, 0x68, 0x75, 0xec, 0x5d, 0xfb, 0x44, 0x60, 0xa4, 0x79, 0x1c,
	0x4c, 0xe9, 0x16, 0xfc, 0x8f, 0x48, 0x61, 0xfb, 0xba, 0xce, 0xa9, 0xe6, 0xe0, 0xf8, 0x5a, 0xf9,
	0x8c, 0xc0, 0x98, 0xea, 0x05, 0xba, 0xce, 0x87, 0x27, 0xee, 0x85, 0x25, 0x1a, 0x81, 0xb0, 0x77,
	0xdc, 0x93, 0x15, 0x4a, 0x15, 0xea, 0x17, 0x87, 0x0a, 0xd8, 0xf3, 0xd7, 0x05, 0xfc, 0x4c, 0x60,
	0x3c, 0x9e, 0xe4, 0x5f, 0x2e, 0xe2, 0xec, 0x9b, 0x14, 0xf4, 0x49, 0x74, 0xfa, 0x9c, 0x40, 0x52,
	0x2d, 0x4c, 0x9a, 0x8d, 0x03, 0x3b, 0xba, 0xa3, 0xb5, 0xe9, 0x8e, 0x6c, 0x55, 0x64, 0x63, 0xe2,
	0xe9, 0xb7, 0x5f, 0xaf, 0x7b, 0xc6, 0xa9, 0xce, 0x5a, 0xbe, 0x14, 0xe8, 0x3b, 0x02, 0x27, 0x1b,
	0xd7, 0x2f, 0x9d, 0x69, 0x19, 0xa5, 0xc9, 0x16, 0xd7, 0x72, 0x5d, 0x28, 0x90, 0xce, 0x94, 0x74,
	0x93, 0x74, 0x22, 0x8e, 0x0e, 0xb7, 0x11, 0x5b, 0x93, 0x6a, 0xfa, 0x8a, 0x40, 0x12, 0xf9, 0x5a,
	0x57, 0x2c, 0x4a, 0x36, 0xdd, 0x91, 0x2d, 0x32, 0x31, 0xc9, 0x34, 0x45, 0x33, 0xed, 0x98, 0xb6,
	0xe5, 0x5b, 0x63, 0x87, 0xbe, 0x20, 0xd0, 0x8f, 0xdb, 0x97, 0x76, 0x12, 0xa9, 0xd6, 0xc8, 0xf3,
	0x9d, 0x19, 0x23, 0x57, 0x46, 0x72, 0x9d, 0xa5, 0x63, 0x6d, 0xb8, 0xe8, 0x17, 0x02, 0x03, 0x47,
	0xe6, 0x99, 0xce, 0xb7, 0x0c, 0x16, 0xb7, 0x9c, 0xb5, 0x4b, 0xdd, 0xca, 0x90, 0x76, 0x5e, 0xd2,
	0x32, 0x7a, 0x21, 0x8e, 0x36, 0xfc, 0x61, 0xb1, 0xed, 0xfa, 0xf2, 0xdf, 0xa1, 0x1f, 0x08, 0x9c,
	0x3a, 0xb4, 0x13, 0xe9, 0x5c, 0xeb, 0x79, 0x6f, 0xba, 0xa9, 0xb5, 0x8b, 0xdd, 0x89, 0x90, 0x7a,
	0x46, 0x52, 0x67, 0xe9, 0x64, 0x5b, 0x6a, 0x57, 0x79, 0xa0, 0x5f, 0x09, 0x0c, 0x36, 0xd9, 0x41,
	0xf4, 0x72, 0xeb, 0xba, 0xc5, 0xee, 0x4f, 0xed, 0x4a, 0xf7, 0x42, 0x84, 0x5f, 0x94, 0xf0, 0xd7,
	0xe8, 0xd5, 0xb6, 0xf0, 0xc5, 0xad, 0x95, 0xda, 0x4a, 0xae, 0xd5, 0x9f, 0x7b, 0x3b, 0xf9, 0xf9,
	0xdd, 0x7d, 0x9d, 0xec, 0xed, 0xeb, 0xe4, 0xe7, 0xbe, 0x4e, 0x5e, 0x1e, 0xe8, 0x89, 0xbd, 0x03,
	0x3d, 0xf1, 0xfd, 0x40, 0x4f, 0x3c, 0x18, 0xae, 0xf9, 0x7c, 0xd2, 0xe8, 0x35, 0xd8, 0x72, 0xb9,
	0x5f, 0x4c, 0xca, 0xbf, 0x94, 0x73, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x44, 0xb0, 0x16, 0x01,
	0x51, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries the module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// LatestBeacon queries the most recently stored beacon.
	LatestBeacon(ctx context.Context, in *QueryLatestBeaconRequest, opts ...grpc.CallOption) (*QueryLatestBeaconResponse, error)
	// Beacon queries a beacon by its round number.
	Beacon(ctx context.Context, in *QueryBeaconRequest, opts ...grpc.CallOption) (*QueryBeaconResponse, error)
	// Beacons queries beacons with pagination.
	Beacons(ctx context.Context, in *QueryBeaconsRequest, opts ...grpc.CallOption) (*QueryBeaconsResponse, error)
	// RandomnessRequest queries a specific randomness request by ID.
	RandomnessRequest(ctx context.Context, in *QueryRandomnessRequestRequest, opts ...grpc.CallOption) (*QueryRandomnessRequestResponse, error)
	// PendingRequests queries all pending randomness requests with pagination.
	PendingRequests(ctx context.Context, in *QueryPendingRequestsRequest, opts ...grpc.CallOption) (*QueryPendingRequestsResponse, error)
	// RequestsByRequester queries randomness requests by requester address with pagination.
	RequestsByRequester(ctx context.Context, in *QueryRequestsByRequesterRequest, opts ...grpc.CallOption) (*QueryRequestsByRequesterResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/seocheon.randomness.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LatestBeacon(ctx context.Context, in *QueryLatestBeaconRequest, opts ...grpc.CallOption) (*QueryLatestBeaconResponse, error) {
	out := new(QueryLatestBeaconResponse)
	err := c.cc.Invoke(ctx, "/seocheon.randomness.v1.Query/LatestBeacon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Beacon(ctx context.Context, in *QueryBeaconRequest, opts ...grpc.CallOption) (*QueryBeaconResponse, error) {
	out := new(QueryBeaconResponse)
	err := c.cc.Invoke(ctx, "/seocheon.randomness.v1.Query/Beacon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Beacons(ctx context.Context, in *QueryBeaconsRequest, opts ...grpc.CallOption) (*QueryBeaconsResponse, error) {
	out := new(QueryBeaconsResponse)
	err := c.cc.Invoke(ctx, "/seocheon.randomness.v1.Query/Beacons", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RandomnessRequest(ctx context.Context, in *QueryRandomnessRequestRequest, opts ...grpc.CallOption) (*QueryRandomnessRequestResponse, error) {
	out := new(QueryRandomnessRequestResponse)
	err := c.cc.Invoke(ctx, "/seocheon.randomness.v1.Query/RandomnessRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingRequests(ctx context.Context, in *QueryPendingRequestsRequest, opts ...grpc.CallOption) (*QueryPendingRequestsResponse, error) {
	out := new(QueryPendingRequestsResponse)
	err := c.cc.Invoke(ctx, "/seocheon.randomness.v1.Query/PendingRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RequestsByRequester(ctx context.Context, in *QueryRequestsByRequesterRequest, opts ...grpc.CallOption) (*QueryRequestsByRequesterResponse, error) {
	out := new(QueryRequestsByRequesterResponse)
	err := c.cc.Invoke(ctx, "/seocheon.randomness.v1.Query/RequestsByRequester", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params queries the module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// LatestBeacon queries the most recently stored beacon.
	LatestBeacon(context.Context, *QueryLatestBeaconRequest) (*QueryLatestBeaconResponse, error)
	// Beacon queries a beacon by its round number.
	Beacon(context.Context, *QueryBeaconRequest) (*QueryBeaconResponse, error)
	// Beacons queries beacons with pagination.
	Beacons(context.Context, *QueryBeaconsRequest) (*QueryBeaconsResponse, error)
	// RandomnessRequest queries a specific randomness request by ID.
	RandomnessRequest(context.Context, *QueryRandomnessRequestRequest) (*QueryRandomnessRequestResponse, error)
	// PendingRequests queries all pending randomness requests with pagination.
	PendingRequests(context.Context, *QueryPendingRequestsRequest) (*QueryPendingRequestsResponse, error)
	// RequestsByRequester queries randomness requests by requester address with pagination.
	RequestsByRequester(context.Context, *QueryRequestsByRequesterRequest) (*QueryRequestsByRequesterResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) LatestBeacon(ctx context.Context, req *QueryLatestBeaconRequest) (*QueryLatestBeaconResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LatestBeacon not implemented")
}
func (*UnimplementedQueryServer) Beacon(ctx context.Context, req *QueryBeaconRequest) (*QueryBeaconResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Beacon not implemented")
}
func (*UnimplementedQueryServer) Beacons(ctx context.Context, req *QueryBeaconsRequest) (*QueryBeaconsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Beacons not implemented")
}
func (*UnimplementedQueryServer) RandomnessRequest(ctx context.Context, req *QueryRandomnessRequestRequest) (*QueryRandomnessRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandomnessRequest not implemented")
}
func (*UnimplementedQueryServer) PendingRequests(ctx context.Context, req *QueryPendingRequestsRequest) (*QueryPendingRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingRequests not implemented")
}
func (*UnimplementedQueryServer) RequestsByRequester(ctx context.Context, req *QueryRequestsByRequesterRequest) (*QueryRequestsByRequesterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestsByRequester not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seocheon.randomness.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LatestBeacon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLatestBeaconRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LatestBeacon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seocheon.randomness.v1.Query/LatestBeacon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LatestBeacon(ctx, req.(*QueryLatestBeaconRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Beacon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBeaconRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Beacon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seocheon.randomness.v1.Query/Beacon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Beacon(ctx, req.(*QueryBeaconRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Beacons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBeaconsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Beacons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seocheon.randomness.v1.Query/Beacons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Beacons(ctx, req.(*QueryBeaconsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RandomnessRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRandomnessRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RandomnessRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seocheon.randomness.v1.Query/RandomnessRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RandomnessRequest(ctx, req.(*QueryRandomnessRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seocheon.randomness.v1.Query/PendingRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingRequests(ctx, req.(*QueryPendingRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RequestsByRequester_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequestsByRequesterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RequestsByRequester(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seocheon.randomness.v1.Query/RequestsByRequester",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RequestsByRequester(ctx, req.(*QueryRequestsByRequesterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seocheon.randomness.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "LatestBeacon",
			Handler:    _Query_LatestBeacon_Handler,
		},
		{
			MethodName: "Beacon",
			Handler:    _Query_Beacon_Handler,
		},
		{
			MethodName: "Beacons",
			Handler:    _Query_Beacons_Handler,
		},
		{
			MethodName: "RandomnessRequest",
			Handler:    _Query_RandomnessRequest_Handler,
		},
		{
			MethodName: "PendingRequests",
			Handler:    _Query_PendingRequests_Handler,
		},
		{
			MethodName: "RequestsByRequester",
			Handler:    _Query_RequestsByRequester_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seocheon/randomness/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryLatestBeaconRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLatestBeaconRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLatestBeaconRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryLatestBeaconResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLatestBeaconResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLatestBeaconResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Beacon.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryBeaconRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBeaconRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBeaconRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Round != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryBeaconResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBeaconResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBeaconResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Beacon.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryBeaconsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBeaconsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBeaconsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryBeaconsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBeaconsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBeaconsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Beacons) > 0 {
		for iNdEx := len(m.Beacons) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Beacons[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryRandomnessRequestRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRandomnessRequestRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRandomnessRequestRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryRandomnessRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRandomnessRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRandomnessRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Request.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryPendingRequestsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingRequestsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingRequestsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPendingRequestsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingRequestsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingRequestsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Requests) > 0 {
		for iNdEx := len(m.Requests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Requests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryRequestsByRequesterRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRequestsByRequesterRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRequestsByRequesterRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Requester) > 0 {
		i -= len(m.Requester)
		copy(dAtA[i:], m.Requester)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Requester)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRequestsByRequesterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRequestsByRequesterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRequestsByRequesterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Requests) > 0 {
		for iNdEx := len(m.Requests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Requests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryLatestBeaconRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryLatestBeaconResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Beacon.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryBeaconRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Round != 0 {
		n += 1 + sovQuery(uint64(m.Round))
	}
	return n
}

func (m *QueryBeaconResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Beacon.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryBeaconsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBeaconsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Beacons) > 0 {
		for _, e := range m.Beacons {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRandomnessRequestRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovQuery(uint64(m.RequestId))
	}
	return n
}

func (m *QueryRandomnessRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Request.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryPendingRequestsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPendingRequestsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Requests) > 0 {
		for _, e := range m.Requests {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRequestsByRequesterRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Requester)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRequestsByRequesterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Requests) > 0 {
		for _, e := range m.Requests {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLatestBeaconRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLatestBeaconRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLatestBeaconRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLatestBeaconResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLatestBeaconResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLatestBeaconResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Beacon", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Beacon.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBeaconRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBeaconRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBeaconRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBeaconResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBeaconResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBeaconResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Beacon", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Beacon.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBeaconsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBeaconsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBeaconsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBeaconsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBeaconsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBeaconsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Beacons", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Beacons = append(m.Beacons, Beacon{})
			if err := m.Beacons[len(m.Beacons)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRandomnessRequestRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRandomnessRequestRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRandomnessRequestRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRandomnessRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRandomnessRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRandomnessRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Request", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Request.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPendingRequestsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingRequestsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingRequestsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPendingRequestsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingRequestsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingRequestsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requests = append(m.Requests, RandomnessRequest{})
			if err := m.Requests[len(m.Requests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRequestsByRequesterRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRequestsByRequesterRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRequestsByRequesterRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requester", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requester = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRequestsByRequesterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRequestsByRequesterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRequestsByRequesterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requests = append(m.Requests, RandomnessRequest{})
			if err := m.Requests[len(m.Requests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
