// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: seocheon/activity/v1/activity.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ActivityRecord represents an on-chain activity submission.
type ActivityRecord struct {
	// node_id is the submitting node's identifier.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// epoch is the epoch number when this activity was submitted.
	Epoch int64 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// sequence is the sequential index within the node's epoch activities.
	Sequence uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// submitter is the agent_address that signed the transaction.
	Submitter string `protobuf:"bytes,4,opt,name=submitter,proto3" json:"submitter,omitempty"`
	// activity_hash is the SHA-256 hash of the activity content (32 bytes, hex-encoded).
	ActivityHash string `protobuf:"bytes,5,opt,name=activity_hash,json=activityHash,proto3" json:"activity_hash,omitempty"`
	// content_uri is the URI pointing to the off-chain activity report.
	ContentUri string `protobuf:"bytes,6,opt,name=content_uri,json=contentUri,proto3" json:"content_uri,omitempty"`
	// block_height is the block at which this activity was submitted.
	BlockHeight int64 `protobuf:"varint,7,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *ActivityRecord) Reset()         { *m = ActivityRecord{} }
func (m *ActivityRecord) String() string { return proto.CompactTextString(m) }
func (*ActivityRecord) ProtoMessage()    {}
func (*ActivityRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd477915e9ec597, []int{0}
}
func (m *ActivityRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActivityRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActivityRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActivityRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityRecord.Merge(m, src)
}
func (m *ActivityRecord) XXX_Size() int {
	return m.Size()
}
func (m *ActivityRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityRecord proto.InternalMessageInfo

func (m *ActivityRecord) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ActivityRecord) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *ActivityRecord) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ActivityRecord) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *ActivityRecord) GetActivityHash() string {
	if m != nil {
		return m.ActivityHash
	}
	return ""
}

func (m *ActivityRecord) GetContentUri() string {
	if m != nil {
		return m.ContentUri
	}
	return ""
}

func (m *ActivityRecord) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

// EpochActivitySummary tracks a node's activity summary for a given epoch.
type EpochActivitySummary struct {
	// total_activities is the total number of activities submitted in the epoch.
	TotalActivities uint64 `protobuf:"varint,1,opt,name=total_activities,json=totalActivities,proto3" json:"total_activities,omitempty"`
	// active_windows is the number of distinct windows with at least one activity.
	ActiveWindows uint64 `protobuf:"varint,2,opt,name=active_windows,json=activeWindows,proto3" json:"active_windows,omitempty"`
	// eligible indicates whether the node met the minimum active windows requirement.
	Eligible bool `protobuf:"varint,3,opt,name=eligible,proto3" json:"eligible,omitempty"`
}

func (m *EpochActivitySummary) Reset()         { *m = EpochActivitySummary{} }
func (m *EpochActivitySummary) String() string { return proto.CompactTextString(m) }
func (*EpochActivitySummary) ProtoMessage()    {}
func (*EpochActivitySummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd477915e9ec597, []int{1}
}
func (m *EpochActivitySummary) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochActivitySummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochActivitySummary.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochActivitySummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochActivitySummary.Merge(m, src)
}
func (m *EpochActivitySummary) XXX_Size() int {
	return m.Size()
}
func (m *EpochActivitySummary) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochActivitySummary.DiscardUnknown(m)
}

var xxx_messageInfo_EpochActivitySummary proto.InternalMessageInfo

func (m *EpochActivitySummary) GetTotalActivities() uint64 {
	if m != nil {
		return m.TotalActivities
	}
	return 0
}

func (m *EpochActivitySummary) GetActiveWindows() uint64 {
	if m != nil {
		return m.ActiveWindows
	}
	return 0
}

func (m *EpochActivitySummary) GetEligible() bool {
	if m != nil {
		return m.Eligible
	}
	return false
}

func init() {
	proto.RegisterType((*ActivityRecord)(nil), "seocheon.activity.v1.ActivityRecord")
	proto.RegisterType((*EpochActivitySummary)(nil), "seocheon.activity.v1.EpochActivitySummary")
}

func init() {
	proto.RegisterFile("seocheon/activity/v1/activity.proto", fileDescriptor_4fd477915e9ec597)
}

var fileDescriptor_4fd477915e9ec597 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x91, 0xcd, 0x6a, 0xea, 0x40,
	0x14, 0xc7, 0x9d, 0x6b, 0xfc, 0x1a, 0xbd, 0xde, 0xcb, 0x10, 0x68, 0x2a, 0x25, 0x5a, 0xa5, 0x60,
	0x37, 0x8a, 0xb8, 0xeb, 0xce, 0x42, 0xc1, 0x6e, 0x53, 0x4a, 0xa1, 0x9b, 0x90, 0x8f, 0x43, 0x66,
	0x68, 0xcc, 0xd8, 0xcc, 0x44, 0xeb, 0x2b, 0x74, 0xd5, 0x47, 0xe8, 0xe3, 0x74, 0xe9, 0xb2, 0xcb,
	0xa2, 0x1b, 0x1f, 0xa3, 0x64, 0x62, 0xe2, 0xee, 0x9c, 0x5f, 0x7e, 0x64, 0xfe, 0xe7, 0x1c, 0x3c,
	0x10, 0xc0, 0x3d, 0x0a, 0x3c, 0x1a, 0x3b, 0x9e, 0x64, 0x2b, 0x26, 0x37, 0xe3, 0xd5, 0xa4, 0xa8,
	0x47, 0xcb, 0x98, 0x4b, 0x4e, 0xf4, 0x5c, 0x1a, 0x15, 0x1f, 0x56, 0x93, 0x8e, 0x1e, 0xf0, 0x80,
	0x2b, 0x61, 0x9c, 0x56, 0x99, 0xdb, 0x3f, 0x20, 0xdc, 0x9e, 0x1d, 0x2d, 0x0b, 0x3c, 0x1e, 0xfb,
	0xe4, 0x0c, 0xd7, 0x22, 0xee, 0x83, 0xcd, 0x7c, 0x03, 0xf5, 0xd0, 0xb0, 0x61, 0x55, 0xd3, 0xf6,
	0xde, 0x27, 0x3a, 0xae, 0xc0, 0x92, 0x7b, 0xd4, 0xf8, 0xd3, 0x43, 0xc3, 0xb2, 0x95, 0x35, 0xa4,
	0x83, 0xeb, 0x02, 0x5e, 0x13, 0x88, 0x3c, 0x30, 0xca, 0x3d, 0x34, 0xd4, 0xac, 0xa2, 0x27, 0x17,
	0xb8, 0x21, 0x12, 0x77, 0xc1, 0xa4, 0x84, 0xd8, 0xd0, 0xd4, 0xcf, 0x4e, 0x80, 0x0c, 0xf0, 0xdf,
	0x3c, 0xa0, 0x4d, 0x1d, 0x41, 0x8d, 0x8a, 0x32, 0x5a, 0x39, 0x9c, 0x3b, 0x82, 0x92, 0x2e, 0x6e,
	0x7a, 0x3c, 0x92, 0x10, 0x49, 0x3b, 0x89, 0x99, 0x51, 0x55, 0x0a, 0x3e, 0xa2, 0xc7, 0x98, 0x91,
	0x4b, 0xdc, 0x72, 0x43, 0xee, 0xbd, 0xd8, 0x14, 0x58, 0x40, 0xa5, 0x51, 0x53, 0xe1, 0x9a, 0x8a,
	0xcd, 0x15, 0xba, 0xd1, 0x0e, 0x9f, 0x5d, 0xd4, 0x7f, 0x47, 0x58, 0xbf, 0x4b, 0x23, 0xe7, 0xf3,
	0x3e, 0x24, 0x8b, 0x85, 0x13, 0x6f, 0xc8, 0x35, 0xfe, 0x2f, 0xb9, 0x74, 0x42, 0xfb, 0xf8, 0x30,
	0x03, 0xa1, 0x26, 0xd7, 0xac, 0x7f, 0x8a, 0xcf, 0x0a, 0x4c, 0xae, 0x70, 0x5b, 0x49, 0x60, 0xaf,
	0x59, 0xe4, 0xf3, 0xb5, 0x50, 0xbb, 0xd0, 0xac, 0x6c, 0x10, 0x78, 0xca, 0x60, 0xba, 0x13, 0x08,
	0x59, 0xc0, 0xdc, 0x30, 0xdb, 0x49, 0xdd, 0x2a, 0xfa, 0x2c, 0xcc, 0xed, 0xf4, 0x6b, 0x67, 0xa2,
	0xed, 0xce, 0x44, 0x3f, 0x3b, 0x13, 0x7d, 0xec, 0xcd, 0xd2, 0x76, 0x6f, 0x96, 0xbe, 0xf7, 0x66,
	0xe9, 0xf9, 0xbc, 0x38, 0xf1, 0xdb, 0xe9, 0xc8, 0x72, 0xb3, 0x04, 0xe1, 0x56, 0xd5, 0xcd, 0xa6,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x70, 0xa0, 0x92, 0x06, 0x02, 0x00, 0x00,
}

func (this *ActivityRecord) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ActivityRecord)
	if !ok {
		that2, ok := that.(ActivityRecord)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.NodeId != that1.NodeId {
		return false
	}
	if this.Epoch != that1.Epoch {
		return false
	}
	if this.Sequence != that1.Sequence {
		return false
	}
	if this.Submitter != that1.Submitter {
		return false
	}
	if this.ActivityHash != that1.ActivityHash {
		return false
	}
	if this.ContentUri != that1.ContentUri {
		return false
	}
	if this.BlockHeight != that1.BlockHeight {
		return false
	}
	return true
}
func (this *EpochActivitySummary) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EpochActivitySummary)
	if !ok {
		that2, ok := that.(EpochActivitySummary)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TotalActivities != that1.TotalActivities {
		return false
	}
	if this.ActiveWindows != that1.ActiveWindows {
		return false
	}
	if this.Eligible != that1.Eligible {
		return false
	}
	return true
}
func (m *ActivityRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActivityRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActivityRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintActivity(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x38
	}
	if len(m.ContentUri) > 0 {
		i -= len(m.ContentUri)
		copy(dAtA[i:], m.ContentUri)
		i = encodeVarintActivity(dAtA, i, uint64(len(m.ContentUri)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ActivityHash) > 0 {
		i -= len(m.ActivityHash)
		copy(dAtA[i:], m.ActivityHash)
		i = encodeVarintActivity(dAtA, i, uint64(len(m.ActivityHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintActivity(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0x22
	}
	if m.Sequence != 0 {
		i = encodeVarintActivity(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x18
	}
	if m.Epoch != 0 {
		i = encodeVarintActivity(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x10
	}
	if len(m.NodeId) > 0 {
		i -= len(m.NodeId)
		copy(dAtA[i:], m.NodeId)
		i = encodeVarintActivity(dAtA, i, uint64(len(m.NodeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EpochActivitySummary) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochActivitySummary) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochActivitySummary) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Eligible {
		i--
		if m.Eligible {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.ActiveWindows != 0 {
		i = encodeVarintActivity(dAtA, i, uint64(m.ActiveWindows))
		i--
		dAtA[i] = 0x10
	}
	if m.TotalActivities != 0 {
		i = encodeVarintActivity(dAtA, i, uint64(m.TotalActivities))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintActivity(dAtA []byte, offset int, v uint64) int {
	offset -= sovActivity(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ActivityRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovActivity(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovActivity(uint64(m.Epoch))
	}
	if m.Sequence != 0 {
		n += 1 + sovActivity(uint64(m.Sequence))
	}
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovActivity(uint64(l))
	}
	l = len(m.ActivityHash)
	if l > 0 {
		n += 1 + l + sovActivity(uint64(l))
	}
	l = len(m.ContentUri)
	if l > 0 {
		n += 1 + l + sovActivity(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovActivity(uint64(m.BlockHeight))
	}
	return n
}

func (m *EpochActivitySummary) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalActivities != 0 {
		n += 1 + sovActivity(uint64(m.TotalActivities))
	}
	if m.ActiveWindows != 0 {
		n += 1 + sovActivity(uint64(m.ActiveWindows))
	}
	if m.Eligible {
		n += 2
	}
	return n
}

func sovActivity(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozActivity(x uint64) (n int) {
	return sovActivity(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ActivityRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActivity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActivityRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActivityRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActivity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActivity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActivity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActivity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivityHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActivity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActivity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActivityHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActivity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActivity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipActivity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthActivity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochActivitySummary) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActivity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochActivitySummary: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochActivitySummary: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalActivities", wireType)
			}
			m.TotalActivities = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalActivities |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveWindows", wireType)
			}
			m.ActiveWindows = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActiveWindows |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Eligible", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Eligible = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipActivity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthActivity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipActivity(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowActivity
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActivity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActivity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthActivity
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupActivity
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthActivity
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthActivity        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowActivity          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupActivity = fmt.Errorf("proto: unexpected end of group")
)
