// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: seocheon/activity/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe944b457cbd4006, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe944b457cbd4006, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryActivityRequest is the request type for the Query/Activity RPC method.
type QueryActivityRequest struct {
	// activity_hash is the hex-encoded SHA-256 hash to look up.
	ActivityHash string `protobuf:"bytes,1,opt,name=activity_hash,json=activityHash,proto3" json:"activity_hash,omitempty"`
}

func (m *QueryActivityRequest) Reset()         { *m = QueryActivityRequest{} }
func (m *QueryActivityRequest) String() string { return proto.CompactTextString(m) }
func (*QueryActivityRequest) ProtoMessage()    {}
func (*QueryActivityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe944b457cbd4006, []int{2}
}
func (m *QueryActivityRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActivityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActivityRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActivityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActivityRequest.Merge(m, src)
}
func (m *QueryActivityRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryActivityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActivityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActivityRequest proto.InternalMessageInfo

func (m *QueryActivityRequest) GetActivityHash() string {
	if m != nil {
		return m.ActivityHash
	}
	return ""
}

// QueryActivityResponse is the response type for the Query/Activity RPC method.
type QueryActivityResponse struct {
	Activity ActivityRecord `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity"`
}

func (m *QueryActivityResponse) Reset()         { *m = QueryActivityResponse{} }
func (m *QueryActivityResponse) String() string { return proto.CompactTextString(m) }
func (*QueryActivityResponse) ProtoMessage()    {}
func (*QueryActivityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe944b457cbd4006, []int{3}
}
func (m *QueryActivityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActivityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActivityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActivityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActivityResponse.Merge(m, src)
}
func (m *QueryActivityResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryActivityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActivityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActivityResponse proto.InternalMessageInfo

func (m *QueryActivityResponse) GetActivity() ActivityRecord {
	if m != nil {
		return m.Activity
	}
	return ActivityRecord{}
}

// QueryActivitiesByNodeRequest is the request type for the Query/ActivitiesByNode RPC method.
type QueryActivitiesByNodeRequest struct {
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Optional epoch filter. If 0, returns all epochs.
	Epoch      int64              `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryActivitiesByNodeRequest) Reset()         { *m = QueryActivitiesByNodeRequest{} }
func (m *QueryActivitiesByNodeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryActivitiesByNodeRequest) ProtoMessage()    {}
func (*QueryActivitiesByNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe944b457cbd4006, []int{4}
}
func (m *QueryActivitiesByNodeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActivitiesByNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActivitiesByNodeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActivitiesByNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActivitiesByNodeRequest.Merge(m, src)
}
func (m *QueryActivitiesByNodeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryActivitiesByNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActivitiesByNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActivitiesByNodeRequest proto.InternalMessageInfo

func (m *QueryActivitiesByNodeRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *QueryActivitiesByNodeRequest) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *QueryActivitiesByNodeRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryActivitiesByNodeResponse is the response type for the Query/ActivitiesByNode RPC method.
type QueryActivitiesByNodeResponse struct {
	Activities []ActivityRecord    `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryActivitiesByNodeResponse) Reset()         { *m = QueryActivitiesByNodeResponse{} }
func (m *QueryActivitiesByNodeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryActivitiesByNodeResponse) ProtoMessage()    {}
func (*QueryActivitiesByNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe944b457cbd4006, []int{5}
}
func (m *QueryActivitiesByNodeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActivitiesByNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActivitiesByNodeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActivitiesByNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActivitiesByNodeResponse.Merge(m, src)
}
func (m *QueryActivitiesByNodeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryActivitiesByNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActivitiesByNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActivitiesByNodeResponse proto.InternalMessageInfo

func (m *QueryActivitiesByNodeResponse) GetActivities() []ActivityRecord {
	if m != nil {
		return m.Activities
	}
	return nil
}

func (m *QueryActivitiesByNodeResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryActivitiesByBlockRequest is the request type for the Query/ActivitiesByBlock RPC method.
type QueryActivitiesByBlockRequest struct {
	BlockHeight int64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *QueryActivitiesByBlockRequest) Reset()         { *m = QueryActivitiesByBlockRequest{} }
func (m *QueryActivitiesByBlockRequest) String() string { return proto.CompactTextString(m) }
func (*QueryActivitiesByBlockRequest) ProtoMessage()    {}
func (*QueryActivitiesByBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe944b457cbd4006, []int{6}
}
func (m *QueryActivitiesByBlockRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActivitiesByBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActivitiesByBlockRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActivitiesByBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActivitiesByBlockRequest.Merge(m, src)
}
func (m *QueryActivitiesByBlockRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryActivitiesByBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActivitiesByBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActivitiesByBlockRequest proto.InternalMessageInfo

func (m *QueryActivitiesByBlockRequest) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

// QueryActivitiesByBlockResponse is the response type for the Query/ActivitiesByBlock RPC method.
type QueryActivitiesByBlockResponse struct {
	Activities []ActivityRecord `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities"`
}

func (m *QueryActivitiesByBlockResponse) Reset()         { *m = QueryActivitiesByBlockResponse{} }
func (m *QueryActivitiesByBlockResponse) String() string { return proto.CompactTextString(m) }
func (*QueryActivitiesByBlockResponse) ProtoMessage()    {}
func (*QueryActivitiesByBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe944b457cbd4006, []int{7}
}
func (m *QueryActivitiesByBlockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActivitiesByBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActivitiesByBlockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActivitiesByBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActivitiesByBlockResponse.Merge(m, src)
}
func (m *QueryActivitiesByBlockResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryActivitiesByBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActivitiesByBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActivitiesByBlockResponse proto.InternalMessageInfo

func (m *QueryActivitiesByBlockResponse) GetActivities() []ActivityRecord {
	if m != nil {
		return m.Activities
	}
	return nil
}

// QueryEpochInfoRequest is the request type for the Query/EpochInfo RPC method.
type QueryEpochInfoRequest struct {
}

func (m *QueryEpochInfoRequest) Reset()         { *m = QueryEpochInfoRequest{} }
func (m *QueryEpochInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEpochInfoRequest) ProtoMessage()    {}
func (*QueryEpochInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe944b457cbd4006, []int{8}
}
func (m *QueryEpochInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEpochInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEpochInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEpochInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEpochInfoRequest.Merge(m, src)
}
func (m *QueryEpochInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEpochInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEpochInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEpochInfoRequest proto.InternalMessageInfo

// QueryEpochInfoResponse is the response type for the Query/EpochInfo RPC method.
type QueryEpochInfoResponse struct {
	// current_epoch is the current epoch number.
	CurrentEpoch int64 `protobuf:"varint,1,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	// current_window is the current window number within the epoch.
	CurrentWindow int64 `protobuf:"varint,2,opt,name=current_window,json=currentWindow,proto3" json:"current_window,omitempty"`
	// epoch_start_block is the first block of the current epoch.
	EpochStartBlock int64 `protobuf:"varint,3,opt,name=epoch_start_block,json=epochStartBlock,proto3" json:"epoch_start_block,omitempty"`
	// blocks_until_next_epoch is the remaining blocks until the next epoch boundary.
	BlocksUntilNextEpoch int64 `protobuf:"varint,4,opt,name=blocks_until_next_epoch,json=blocksUntilNextEpoch,proto3" json:"blocks_until_next_epoch,omitempty"`
}

func (m *QueryEpochInfoResponse) Reset()         { *m = QueryEpochInfoResponse{} }
func (m *QueryEpochInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEpochInfoResponse) ProtoMessage()    {}
func (*QueryEpochInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe944b457cbd4006, []int{9}
}
func (m *QueryEpochInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEpochInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEpochInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEpochInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEpochInfoResponse.Merge(m, src)
}
func (m *QueryEpochInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEpochInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEpochInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEpochInfoResponse proto.InternalMessageInfo

func (m *QueryEpochInfoResponse) GetCurrentEpoch() int64 {
	if m != nil {
		return m.CurrentEpoch
	}
	return 0
}

func (m *QueryEpochInfoResponse) GetCurrentWindow() int64 {
	if m != nil {
		return m.CurrentWindow
	}
	return 0
}

func (m *QueryEpochInfoResponse) GetEpochStartBlock() int64 {
	if m != nil {
		return m.EpochStartBlock
	}
	return 0
}

func (m *QueryEpochInfoResponse) GetBlocksUntilNextEpoch() int64 {
	if m != nil {
		return m.BlocksUntilNextEpoch
	}
	return 0
}

// QueryNodeEpochActivityRequest is the request type for the Query/NodeEpochActivity RPC method.
type QueryNodeEpochActivityRequest struct {
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Epoch  int64  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (m *QueryNodeEpochActivityRequest) Reset()         { *m = QueryNodeEpochActivityRequest{} }
func (m *QueryNodeEpochActivityRequest) String() string { return proto.CompactTextString(m) }
func (*QueryNodeEpochActivityRequest) ProtoMessage()    {}
func (*QueryNodeEpochActivityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe944b457cbd4006, []int{10}
}
func (m *QueryNodeEpochActivityRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNodeEpochActivityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNodeEpochActivityRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNodeEpochActivityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNodeEpochActivityRequest.Merge(m, src)
}
func (m *QueryNodeEpochActivityRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryNodeEpochActivityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNodeEpochActivityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNodeEpochActivityRequest proto.InternalMessageInfo

func (m *QueryNodeEpochActivityRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *QueryNodeEpochActivityRequest) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

// QueryNodeEpochActivityResponse is the response type for the Query/NodeEpochActivity RPC method.
type QueryNodeEpochActivityResponse struct {
	Summary EpochActivitySummary `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary"`
	// quota_used is the number of activities submitted in this epoch.
	QuotaUsed uint64 `protobuf:"varint,2,opt,name=quota_used,json=quotaUsed,proto3" json:"quota_used,omitempty"`
	// quota_limit is the maximum allowed activities for this epoch.
	QuotaLimit uint64 `protobuf:"varint,3,opt,name=quota_limit,json=quotaLimit,proto3" json:"quota_limit,omitempty"`
}

func (m *QueryNodeEpochActivityResponse) Reset()         { *m = QueryNodeEpochActivityResponse{} }
func (m *QueryNodeEpochActivityResponse) String() string { return proto.CompactTextString(m) }
func (*QueryNodeEpochActivityResponse) ProtoMessage()    {}
func (*QueryNodeEpochActivityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe944b457cbd4006, []int{11}
}
func (m *QueryNodeEpochActivityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNodeEpochActivityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNodeEpochActivityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNodeEpochActivityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNodeEpochActivityResponse.Merge(m, src)
}
func (m *QueryNodeEpochActivityResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryNodeEpochActivityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNodeEpochActivityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNodeEpochActivityResponse proto.InternalMessageInfo

func (m *QueryNodeEpochActivityResponse) GetSummary() EpochActivitySummary {
	if m != nil {
		return m.Summary
	}
	return EpochActivitySummary{}
}

func (m *QueryNodeEpochActivityResponse) GetQuotaUsed() uint64 {
	if m != nil {
		return m.QuotaUsed
	}
	return 0
}

func (m *QueryNodeEpochActivityResponse) GetQuotaLimit() uint64 {
	if m != nil {
		return m.QuotaLimit
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "seocheon.activity.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "seocheon.activity.v1.QueryParamsResponse")
	proto.RegisterType((*QueryActivityRequest)(nil), "seocheon.activity.v1.QueryActivityRequest")
	proto.RegisterType((*QueryActivityResponse)(nil), "seocheon.activity.v1.QueryActivityResponse")
	proto.RegisterType((*QueryActivitiesByNodeRequest)(nil), "seocheon.activity.v1.QueryActivitiesByNodeRequest")
	proto.RegisterType((*QueryActivitiesByNodeResponse)(nil), "seocheon.activity.v1.QueryActivitiesByNodeResponse")
	proto.RegisterType((*QueryActivitiesByBlockRequest)(nil), "seocheon.activity.v1.QueryActivitiesByBlockRequest")
	proto.RegisterType((*QueryActivitiesByBlockResponse)(nil), "seocheon.activity.v1.QueryActivitiesByBlockResponse")
	proto.RegisterType((*QueryEpochInfoRequest)(nil), "seocheon.activity.v1.QueryEpochInfoRequest")
	proto.RegisterType((*QueryEpochInfoResponse)(nil), "seocheon.activity.v1.QueryEpochInfoResponse")
	proto.RegisterType((*QueryNodeEpochActivityRequest)(nil), "seocheon.activity.v1.QueryNodeEpochActivityRequest")
	proto.RegisterType((*QueryNodeEpochActivityResponse)(nil), "seocheon.activity.v1.QueryNodeEpochActivityResponse")
}

func init() { proto.RegisterFile("seocheon/activity/v1/query.proto", fileDescriptor_fe944b457cbd4006) }

var fileDescriptor_fe944b457cbd4006 = []byte{
	// 908 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x41, 0x6f, 0x1b, 0x45,
	0x14, 0xc7, 0x33, 0x71, 0x9a, 0x34, 0x2f, 0x29, 0x90, 0xc1, 0x90, 0x60, 0xa5, 0x5b, 0x77, 0x53,
	0x20, 0x18, 0xd8, 0x21, 0x4e, 0xa9, 0x2a, 0x81, 0x40, 0x58, 0xa2, 0xb4, 0x08, 0x45, 0x65, 0xab,
	0x82, 0xc4, 0x65, 0x35, 0xf6, 0x0e, 0xf6, 0x0a, 0x7b, 0xc7, 0xd9, 0x59, 0xbb, 0xb1, 0xac, 0x5c,
	0xe0, 0x0b, 0x54, 0x42, 0x1c, 0xb9, 0x73, 0xe0, 0xc0, 0x01, 0x6e, 0x88, 0x2b, 0x3d, 0x56, 0xe2,
	0xc2, 0x09, 0xa1, 0x04, 0x89, 0xaf, 0xc0, 0x11, 0xed, 0x9b, 0x59, 0xc7, 0x76, 0xd6, 0xae, 0x2d,
	0xf5, 0x62, 0xef, 0xbe, 0x79, 0xff, 0x37, 0xbf, 0x79, 0xef, 0xcd, 0xb3, 0xa1, 0xa8, 0x84, 0xac,
	0x35, 0x84, 0x0c, 0x19, 0xaf, 0xc5, 0x41, 0x37, 0x88, 0x7b, 0xac, 0xbb, 0xc7, 0x0e, 0x3b, 0x22,
	0xea, 0x39, 0xed, 0x48, 0xc6, 0x92, 0xe6, 0x53, 0x0f, 0x27, 0xf5, 0x70, 0xba, 0x7b, 0x85, 0x0d,
	0xde, 0x0a, 0x42, 0xc9, 0xf0, 0x53, 0x3b, 0x16, 0x4a, 0x35, 0xa9, 0x5a, 0x52, 0xb1, 0x2a, 0x57,
	0x42, 0x47, 0x60, 0xdd, 0xbd, 0xaa, 0x88, 0xf9, 0x1e, 0x6b, 0xf3, 0x7a, 0x10, 0xf2, 0x38, 0x90,
	0xa1, 0xf1, 0xcd, 0xd7, 0x65, 0x5d, 0xe2, 0x23, 0x4b, 0x9e, 0x8c, 0x75, 0xbb, 0x2e, 0x65, 0xbd,
	0x29, 0x18, 0x6f, 0x07, 0x8c, 0x87, 0xa1, 0x8c, 0x51, 0xa2, 0xcc, 0xea, 0x4e, 0x26, 0xea, 0x00,
	0x4a, 0x3b, 0x5d, 0xcd, 0x74, 0x6a, 0xf3, 0x88, 0xb7, 0x4c, 0x1c, 0x3b, 0x0f, 0xf4, 0xd3, 0x84,
	0xee, 0x2e, 0x1a, 0x5d, 0x71, 0xd8, 0x11, 0x2a, 0xb6, 0x3f, 0x83, 0xe7, 0x47, 0xac, 0xaa, 0x2d,
	0x43, 0x25, 0xe8, 0xfb, 0xb0, 0xac, 0xc5, 0x5b, 0xa4, 0x48, 0x76, 0xd7, 0xca, 0xdb, 0x4e, 0x56,
	0x3a, 0x1c, 0xad, 0xaa, 0xac, 0x3e, 0xfa, 0xeb, 0xca, 0xc2, 0x0f, 0xff, 0xfe, 0x54, 0x22, 0xae,
	0x91, 0xd9, 0xef, 0x40, 0x1e, 0xe3, 0x7e, 0x60, 0xbc, 0xcd, 0x7e, 0x74, 0x07, 0x2e, 0xa5, 0x01,
	0xbc, 0x06, 0x57, 0x0d, 0x8c, 0xbf, 0xea, 0xae, 0xa7, 0xc6, 0xdb, 0x5c, 0x35, 0x6c, 0x0f, 0x5e,
	0x18, 0x13, 0x1b, 0xac, 0x5b, 0x70, 0x31, 0x75, 0x34, 0x60, 0xd7, 0xb2, 0xc1, 0xce, 0x94, 0x35,
	0x19, 0xf9, 0x95, 0xa5, 0x04, 0xd0, 0x1d, 0x68, 0xed, 0xef, 0x08, 0x6c, 0x0f, 0xef, 0x10, 0x08,
	0x55, 0xe9, 0x1d, 0x48, 0x5f, 0xa4, 0x98, 0x9b, 0xb0, 0x12, 0x4a, 0x5f, 0x78, 0x81, 0x6f, 0x00,
	0x97, 0x93, 0xd7, 0x3b, 0x3e, 0xcd, 0xc3, 0x05, 0xd1, 0x96, 0xb5, 0xc6, 0xd6, 0x62, 0x91, 0xec,
	0xe6, 0x5c, 0xfd, 0x42, 0x6f, 0x01, 0x9c, 0xd5, 0x7a, 0x2b, 0x87, 0x64, 0xaf, 0x38, 0xba, 0x31,
	0x9c, 0xa4, 0x31, 0x1c, 0xdd, 0x5a, 0xa6, 0x31, 0x9c, 0xbb, 0xbc, 0x9e, 0x6e, 0xe5, 0x0e, 0x29,
	0xed, 0x9f, 0x09, 0x5c, 0x9e, 0xc0, 0x65, 0x32, 0xf0, 0x31, 0x00, 0x1f, 0xac, 0x6d, 0x91, 0x62,
	0x6e, 0xce, 0x1c, 0x0c, 0xa9, 0xe9, 0x47, 0x23, 0xd4, 0x8b, 0x48, 0xfd, 0xea, 0x13, 0xa9, 0x35,
	0xc8, 0x08, 0x76, 0x25, 0x83, 0xba, 0xd2, 0x94, 0xb5, 0xaf, 0xd2, 0x74, 0x5e, 0x85, 0xf5, 0x6a,
	0xf2, 0xee, 0x35, 0x44, 0x50, 0x6f, 0xc4, 0x98, 0xd3, 0x9c, 0xbb, 0x86, 0xb6, 0xdb, 0x68, 0xb2,
	0x9b, 0x60, 0x4d, 0x8a, 0xf1, 0xf4, 0x8f, 0x6e, 0x6f, 0x9a, 0x0e, 0xfb, 0x30, 0x29, 0xdf, 0x9d,
	0xf0, 0x4b, 0x99, 0xde, 0x87, 0xdf, 0x09, 0xbc, 0x38, 0xbe, 0x62, 0xf6, 0xdf, 0x81, 0x4b, 0xb5,
	0x4e, 0x14, 0x89, 0x30, 0xf6, 0x74, 0x0b, 0xe8, 0x53, 0xac, 0x1b, 0x23, 0x0a, 0xe8, 0xcb, 0xf0,
	0x4c, 0xea, 0xf4, 0x20, 0x08, 0x7d, 0xf9, 0xc0, 0x34, 0x4a, 0x2a, 0xfd, 0x1c, 0x8d, 0xb4, 0x04,
	0x1b, 0x18, 0xc3, 0x53, 0x31, 0x8f, 0x62, 0x0f, 0x13, 0x81, 0x7d, 0x93, 0x73, 0x9f, 0xc5, 0x85,
	0x7b, 0x89, 0x1d, 0xcf, 0x4f, 0xdf, 0x86, 0x4d, 0x5c, 0x57, 0x5e, 0x27, 0x8c, 0x83, 0xa6, 0x17,
	0x8a, 0xa3, 0x94, 0x60, 0x09, 0x15, 0x79, 0xbd, 0x7c, 0x3f, 0x59, 0x3d, 0x10, 0x47, 0x9a, 0xc4,
	0x3e, 0x30, 0x45, 0x49, 0xda, 0x07, 0x2d, 0xe3, 0x57, 0x71, 0xbe, 0x1e, 0xb7, 0x7f, 0x24, 0xa6,
	0x42, 0x19, 0x01, 0x07, 0x15, 0x5a, 0x51, 0x9d, 0x56, 0x8b, 0x47, 0xe9, 0xed, 0x2c, 0x65, 0x97,
	0x67, 0x44, 0x7d, 0x4f, 0x2b, 0x4c, 0x91, 0xd2, 0x00, 0xf4, 0x32, 0xc0, 0x61, 0x47, 0xc6, 0xdc,
	0xeb, 0x28, 0xe1, 0x23, 0xc9, 0x92, 0xbb, 0x8a, 0x96, 0xfb, 0x4a, 0xf8, 0xf4, 0x0a, 0xac, 0xe9,
	0xe5, 0x66, 0xd0, 0x0a, 0x62, 0x4c, 0xdd, 0x92, 0xab, 0x15, 0x9f, 0x24, 0x96, 0xf2, 0x7f, 0x2b,
	0x70, 0x01, 0x71, 0xe9, 0x37, 0x04, 0x96, 0xf5, 0xa0, 0xa2, 0xbb, 0xd9, 0x3c, 0xe7, 0xe7, 0x62,
	0xe1, 0xb5, 0x19, 0x3c, 0xf5, 0xa9, 0xed, 0x6b, 0x5f, 0xff, 0xf1, 0xcf, 0xb7, 0x8b, 0x16, 0xdd,
	0x66, 0x53, 0x86, 0x30, 0xfd, 0x9e, 0xc0, 0xc5, 0xf4, 0xc8, 0xb4, 0x34, 0x25, 0xfa, 0x58, 0x99,
	0x0a, 0xaf, 0xcf, 0xe4, 0x6b, 0x58, 0x6e, 0x22, 0x4b, 0x99, 0xbe, 0xc5, 0xa6, 0xfd, 0x6a, 0x04,
	0x42, 0xb1, 0xfe, 0xc8, 0x18, 0x3e, 0xa6, 0xbf, 0x10, 0x78, 0x6e, 0x7c, 0xea, 0xd0, 0xf2, 0x93,
	0xf7, 0x1e, 0x1f, 0x9d, 0x85, 0xfd, 0xb9, 0x34, 0xb3, 0x71, 0x27, 0x8d, 0xa9, 0x58, 0xdf, 0xb4,
	0xeb, 0xf1, 0xd0, 0x39, 0xe8, 0x6f, 0x04, 0x36, 0xce, 0xcd, 0x0c, 0x3a, 0x2b, 0xc4, 0xf0, 0x94,
	0x2a, 0x5c, 0x9f, 0x4f, 0x64, 0xd0, 0xdf, 0x43, 0xf4, 0x9b, 0xf4, 0x46, 0x36, 0xba, 0xbe, 0x9b,
	0xac, 0x3f, 0x3c, 0xff, 0x46, 0x0e, 0xf0, 0x90, 0xc0, 0xea, 0x60, 0xd8, 0xd0, 0x69, 0xd5, 0x1e,
	0x1f, 0x56, 0x85, 0x37, 0x66, 0x73, 0x36, 0xa0, 0xbb, 0x08, 0x6a, 0xd3, 0x62, 0x36, 0x28, 0xde,
	0xf2, 0x37, 0x83, 0x04, 0xe2, 0x57, 0x02, 0x1b, 0xe7, 0x6e, 0xf9, 0xd4, 0x9c, 0x4e, 0x1a, 0x32,
	0x53, 0x73, 0x3a, 0x71, 0x90, 0xd8, 0xef, 0x22, 0xea, 0x0d, 0x7a, 0x7d, 0xb6, 0x76, 0x40, 0x74,
	0xc5, 0xfa, 0xf8, 0x7d, 0x5c, 0xd9, 0x7f, 0x74, 0x62, 0x91, 0xc7, 0x27, 0x16, 0xf9, 0xfb, 0xc4,
	0x22, 0x0f, 0x4f, 0xad, 0x85, 0xc7, 0xa7, 0xd6, 0xc2, 0x9f, 0xa7, 0xd6, 0xc2, 0x17, 0x2f, 0x0d,
	0xc2, 0x1d, 0x9d, 0x05, 0x8c, 0x7b, 0x6d, 0xa1, 0xaa, 0xcb, 0xf8, 0x2f, 0x69, 0xff, 0xff, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x27, 0x6b, 0xc9, 0x48, 0x1a, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries the module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Activity queries a single activity by hash.
	Activity(ctx context.Context, in *QueryActivityRequest, opts ...grpc.CallOption) (*QueryActivityResponse, error)
	// ActivitiesByNode queries activities by node_id with pagination.
	ActivitiesByNode(ctx context.Context, in *QueryActivitiesByNodeRequest, opts ...grpc.CallOption) (*QueryActivitiesByNodeResponse, error)
	// ActivitiesByBlock queries activities submitted at a specific block height.
	ActivitiesByBlock(ctx context.Context, in *QueryActivitiesByBlockRequest, opts ...grpc.CallOption) (*QueryActivitiesByBlockResponse, error)
	// EpochInfo queries current epoch and window information.
	EpochInfo(ctx context.Context, in *QueryEpochInfoRequest, opts ...grpc.CallOption) (*QueryEpochInfoResponse, error)
	// NodeEpochActivity queries a node's activity summary for a given epoch.
	NodeEpochActivity(ctx context.Context, in *QueryNodeEpochActivityRequest, opts ...grpc.CallOption) (*QueryNodeEpochActivityResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/seocheon.activity.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Activity(ctx context.Context, in *QueryActivityRequest, opts ...grpc.CallOption) (*QueryActivityResponse, error) {
	out := new(QueryActivityResponse)
	err := c.cc.Invoke(ctx, "/seocheon.activity.v1.Query/Activity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ActivitiesByNode(ctx context.Context, in *QueryActivitiesByNodeRequest, opts ...grpc.CallOption) (*QueryActivitiesByNodeResponse, error) {
	out := new(QueryActivitiesByNodeResponse)
	err := c.cc.Invoke(ctx, "/seocheon.activity.v1.Query/ActivitiesByNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ActivitiesByBlock(ctx context.Context, in *QueryActivitiesByBlockRequest, opts ...grpc.CallOption) (*QueryActivitiesByBlockResponse, error) {
	out := new(QueryActivitiesByBlockResponse)
	err := c.cc.Invoke(ctx, "/seocheon.activity.v1.Query/ActivitiesByBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EpochInfo(ctx context.Context, in *QueryEpochInfoRequest, opts ...grpc.CallOption) (*QueryEpochInfoResponse, error) {
	out := new(QueryEpochInfoResponse)
	err := c.cc.Invoke(ctx, "/seocheon.activity.v1.Query/EpochInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NodeEpochActivity(ctx context.Context, in *QueryNodeEpochActivityRequest, opts ...grpc.CallOption) (*QueryNodeEpochActivityResponse, error) {
	out := new(QueryNodeEpochActivityResponse)
	err := c.cc.Invoke(ctx, "/seocheon.activity.v1.Query/NodeEpochActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params queries the module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Activity queries a single activity by hash.
	Activity(context.Context, *QueryActivityRequest) (*QueryActivityResponse, error)
	// ActivitiesByNode queries activities by node_id with pagination.
	ActivitiesByNode(context.Context, *QueryActivitiesByNodeRequest) (*QueryActivitiesByNodeResponse, error)
	// ActivitiesByBlock queries activities submitted at a specific block height.
	ActivitiesByBlock(context.Context, *QueryActivitiesByBlockRequest) (*QueryActivitiesByBlockResponse, error)
	// EpochInfo queries current epoch and window information.
	EpochInfo(context.Context, *QueryEpochInfoRequest) (*QueryEpochInfoResponse, error)
	// NodeEpochActivity queries a node's activity summary for a given epoch.
	NodeEpochActivity(context.Context, *QueryNodeEpochActivityRequest) (*QueryNodeEpochActivityResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Activity(ctx context.Context, req *QueryActivityRequest) (*QueryActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Activity not implemented")
}
func (*UnimplementedQueryServer) ActivitiesByNode(ctx context.Context, req *QueryActivitiesByNodeRequest) (*QueryActivitiesByNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivitiesByNode not implemented")
}
func (*UnimplementedQueryServer) ActivitiesByBlock(ctx context.Context, req *QueryActivitiesByBlockRequest) (*QueryActivitiesByBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivitiesByBlock not implemented")
}
func (*UnimplementedQueryServer) EpochInfo(ctx context.Context, req *QueryEpochInfoRequest) (*QueryEpochInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EpochInfo not implemented")
}
func (*UnimplementedQueryServer) NodeEpochActivity(ctx context.Context, req *QueryNodeEpochActivityRequest) (*QueryNodeEpochActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeEpochActivity not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seocheon.activity.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Activity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Activity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seocheon.activity.v1.Query/Activity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Activity(ctx, req.(*QueryActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ActivitiesByNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryActivitiesByNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ActivitiesByNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seocheon.activity.v1.Query/ActivitiesByNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ActivitiesByNode(ctx, req.(*QueryActivitiesByNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ActivitiesByBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryActivitiesByBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ActivitiesByBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seocheon.activity.v1.Query/ActivitiesByBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ActivitiesByBlock(ctx, req.(*QueryActivitiesByBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EpochInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEpochInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EpochInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seocheon.activity.v1.Query/EpochInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EpochInfo(ctx, req.(*QueryEpochInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NodeEpochActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNodeEpochActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NodeEpochActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seocheon.activity.v1.Query/NodeEpochActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NodeEpochActivity(ctx, req.(*QueryNodeEpochActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seocheon.activity.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Activity",
			Handler:    _Query_Activity_Handler,
		},
		{
			MethodName: "ActivitiesByNode",
			Handler:    _Query_ActivitiesByNode_Handler,
		},
		{
			MethodName: "ActivitiesByBlock",
			Handler:    _Query_ActivitiesByBlock_Handler,
		},
		{
			MethodName: "EpochInfo",
			Handler:    _Query_EpochInfo_Handler,
		},
		{
			MethodName: "NodeEpochActivity",
			Handler:    _Query_NodeEpochActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seocheon/activity/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryActivityRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActivityRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActivityRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ActivityHash) > 0 {
		i -= len(m.ActivityHash)
		copy(dAtA[i:], m.ActivityHash)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ActivityHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryActivityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActivityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActivityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Activity.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryActivitiesByNodeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActivitiesByNodeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActivitiesByNodeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Epoch != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x10
	}
	if len(m.NodeId) > 0 {
		i -= len(m.NodeId)
		copy(dAtA[i:], m.NodeId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.NodeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryActivitiesByNodeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActivitiesByNodeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActivitiesByNodeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Activities) > 0 {
		for iNdEx := len(m.Activities) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Activities[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryActivitiesByBlockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActivitiesByBlockRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActivitiesByBlockRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryActivitiesByBlockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActivitiesByBlockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActivitiesByBlockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Activities) > 0 {
		for iNdEx := len(m.Activities) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Activities[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryEpochInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEpochInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEpochInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryEpochInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEpochInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEpochInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlocksUntilNextEpoch != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BlocksUntilNextEpoch))
		i--
		dAtA[i] = 0x20
	}
	if m.EpochStartBlock != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EpochStartBlock))
		i--
		dAtA[i] = 0x18
	}
	if m.CurrentWindow != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CurrentWindow))
		i--
		dAtA[i] = 0x10
	}
	if m.CurrentEpoch != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CurrentEpoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryNodeEpochActivityRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNodeEpochActivityRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNodeEpochActivityRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Epoch != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x10
	}
	if len(m.NodeId) > 0 {
		i -= len(m.NodeId)
		copy(dAtA[i:], m.NodeId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.NodeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryNodeEpochActivityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNodeEpochActivityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNodeEpochActivityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.QuotaLimit != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.QuotaLimit))
		i--
		dAtA[i] = 0x18
	}
	if m.QuotaUsed != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.QuotaUsed))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Summary.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryActivityRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ActivityHash)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryActivityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Activity.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryActivitiesByNodeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovQuery(uint64(m.Epoch))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryActivitiesByNodeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Activities) > 0 {
		for _, e := range m.Activities {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryActivitiesByBlockRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovQuery(uint64(m.BlockHeight))
	}
	return n
}

func (m *QueryActivitiesByBlockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Activities) > 0 {
		for _, e := range m.Activities {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryEpochInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryEpochInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CurrentEpoch != 0 {
		n += 1 + sovQuery(uint64(m.CurrentEpoch))
	}
	if m.CurrentWindow != 0 {
		n += 1 + sovQuery(uint64(m.CurrentWindow))
	}
	if m.EpochStartBlock != 0 {
		n += 1 + sovQuery(uint64(m.EpochStartBlock))
	}
	if m.BlocksUntilNextEpoch != 0 {
		n += 1 + sovQuery(uint64(m.BlocksUntilNextEpoch))
	}
	return n
}

func (m *QueryNodeEpochActivityRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovQuery(uint64(m.Epoch))
	}
	return n
}

func (m *QueryNodeEpochActivityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Summary.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.QuotaUsed != 0 {
		n += 1 + sovQuery(uint64(m.QuotaUsed))
	}
	if m.QuotaLimit != 0 {
		n += 1 + sovQuery(uint64(m.QuotaLimit))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActivityRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActivityRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActivityRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivityHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActivityHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActivityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActivityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActivityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Activity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Activity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActivitiesByNodeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActivitiesByNodeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActivitiesByNodeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActivitiesByNodeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActivitiesByNodeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActivitiesByNodeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Activities", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Activities = append(m.Activities, ActivityRecord{})
			if err := m.Activities[len(m.Activities)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActivitiesByBlockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActivitiesByBlockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActivitiesByBlockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActivitiesByBlockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActivitiesByBlockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActivitiesByBlockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Activities", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Activities = append(m.Activities, ActivityRecord{})
			if err := m.Activities[len(m.Activities)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEpochInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEpochInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEpochInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEpochInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEpochInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEpochInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpoch", wireType)
			}
			m.CurrentEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentEpoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentWindow", wireType)
			}
			m.CurrentWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentWindow |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochStartBlock", wireType)
			}
			m.EpochStartBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochStartBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksUntilNextEpoch", wireType)
			}
			m.BlocksUntilNextEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlocksUntilNextEpoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNodeEpochActivityRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNodeEpochActivityRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNodeEpochActivityRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNodeEpochActivityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNodeEpochActivityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNodeEpochActivityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Summary", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Summary.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuotaUsed", wireType)
			}
			m.QuotaUsed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QuotaUsed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuotaLimit", wireType)
			}
			m.QuotaLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QuotaLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
