// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: seocheon/node/v1/genesis.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the x/node module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// nodes is the list of registered nodes at genesis.
	Nodes []Node `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes"`
	// registration_pool_balance is the initial balance for the Registration Pool.
	RegistrationPoolBalance github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=registration_pool_balance,json=registrationPoolBalance,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"registration_pool_balance"`
	// feegrant_pool_balance is the initial balance for the Feegrant Pool.
	FeegrantPoolBalance github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,4,rep,name=feegrant_pool_balance,json=feegrantPoolBalance,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"feegrant_pool_balance"`
	// boost_pool_balance is the initial balance for the Validator Boost Pool.
	BoostPoolBalance github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,5,rep,name=boost_pool_balance,json=boostPoolBalance,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"boost_pool_balance"`
	// boost_target_epochs is the target number of epochs over which the boost pool is distributed.
	BoostTargetEpochs uint64 `protobuf:"varint,6,opt,name=boost_target_epochs,json=boostTargetEpochs,proto3" json:"boost_target_epochs,omitempty"`
	// delegation_confirmations stores all active delegation confirmation records.
	DelegationConfirmations []DelegationConfirmation `protobuf:"bytes,7,rep,name=delegation_confirmations,json=delegationConfirmations,proto3" json:"delegation_confirmations"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f54ac42f9ebc09, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetNodes() []Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *GenesisState) GetRegistrationPoolBalance() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.RegistrationPoolBalance
	}
	return nil
}

func (m *GenesisState) GetFeegrantPoolBalance() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.FeegrantPoolBalance
	}
	return nil
}

func (m *GenesisState) GetBoostPoolBalance() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.BoostPoolBalance
	}
	return nil
}

func (m *GenesisState) GetBoostTargetEpochs() uint64 {
	if m != nil {
		return m.BoostTargetEpochs
	}
	return 0
}

func (m *GenesisState) GetDelegationConfirmations() []DelegationConfirmation {
	if m != nil {
		return m.DelegationConfirmations
	}
	return nil
}

// DelegationConfirmation stores the expiry epoch for a delegator-validator pair.
type DelegationConfirmation struct {
	// delegator_address is the delegator's account address.
	DelegatorAddress string `protobuf:"bytes,1,opt,name=delegator_address,json=delegatorAddress,proto3" json:"delegator_address,omitempty"`
	// validator_address is the validator's operator address.
	ValidatorAddress string `protobuf:"bytes,2,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	// expiry_epoch is the epoch at which the delegation expires if not confirmed.
	ExpiryEpoch uint64 `protobuf:"varint,3,opt,name=expiry_epoch,json=expiryEpoch,proto3" json:"expiry_epoch,omitempty"`
}

func (m *DelegationConfirmation) Reset()         { *m = DelegationConfirmation{} }
func (m *DelegationConfirmation) String() string { return proto.CompactTextString(m) }
func (*DelegationConfirmation) ProtoMessage()    {}
func (*DelegationConfirmation) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f54ac42f9ebc09, []int{1}
}
func (m *DelegationConfirmation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegationConfirmation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelegationConfirmation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelegationConfirmation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegationConfirmation.Merge(m, src)
}
func (m *DelegationConfirmation) XXX_Size() int {
	return m.Size()
}
func (m *DelegationConfirmation) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegationConfirmation.DiscardUnknown(m)
}

var xxx_messageInfo_DelegationConfirmation proto.InternalMessageInfo

func (m *DelegationConfirmation) GetDelegatorAddress() string {
	if m != nil {
		return m.DelegatorAddress
	}
	return ""
}

func (m *DelegationConfirmation) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *DelegationConfirmation) GetExpiryEpoch() uint64 {
	if m != nil {
		return m.ExpiryEpoch
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "seocheon.node.v1.GenesisState")
	proto.RegisterType((*DelegationConfirmation)(nil), "seocheon.node.v1.DelegationConfirmation")
}

func init() { proto.RegisterFile("seocheon/node/v1/genesis.proto", fileDescriptor_22f54ac42f9ebc09) }

var fileDescriptor_22f54ac42f9ebc09 = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x3f, 0x6f, 0x13, 0x31,
	0x1c, 0x8d, 0x9b, 0x3f, 0xa8, 0x4e, 0x87, 0xe4, 0x4a, 0xdb, 0x6b, 0x11, 0xd7, 0xd0, 0x29, 0x02,
	0x61, 0x2b, 0x41, 0x4c, 0x4c, 0x5c, 0x41, 0x6c, 0xa8, 0x0a, 0x4c, 0x2c, 0x91, 0xef, 0xce, 0xbd,
	0x58, 0xdc, 0xf9, 0x77, 0xb2, 0x4d, 0xd4, 0x2e, 0x4c, 0x8c, 0x0c, 0x2c, 0x7c, 0x07, 0xc4, 0xd4,
	0x8f, 0xd1, 0xb1, 0x23, 0x13, 0xa0, 0x64, 0xe0, 0x6b, 0xa0, 0xb3, 0x2f, 0x51, 0xda, 0x74, 0xed,
	0x92, 0xf8, 0xfc, 0xde, 0xf3, 0x7b, 0x7a, 0xf6, 0x0f, 0x07, 0x9a, 0x43, 0x3c, 0xe1, 0x20, 0xa9,
	0x84, 0x84, 0xd3, 0xe9, 0x80, 0xa6, 0x5c, 0x72, 0x2d, 0x34, 0x29, 0x14, 0x18, 0xf0, 0x3a, 0x0b,
	0x9c, 0x94, 0x38, 0x99, 0x0e, 0x0e, 0xba, 0x2c, 0x17, 0x12, 0xa8, 0xfd, 0x75, 0xa4, 0x83, 0x20,
	0x06, 0x9d, 0x83, 0xa6, 0x11, 0xd3, 0xe5, 0x11, 0x11, 0x37, 0x6c, 0x40, 0x63, 0x10, 0xb2, 0xc2,
	0xef, 0xa7, 0x90, 0x82, 0x5d, 0xd2, 0x72, 0x55, 0xed, 0x3e, 0x58, 0xb3, 0xb6, 0x16, 0x0e, 0x7c,
	0xb8, 0x06, 0x16, 0x4c, 0xb1, 0xbc, 0x8a, 0x75, 0x74, 0xd1, 0xc4, 0x5b, 0x6f, 0x5c, 0xd0, 0x77,
	0x86, 0x19, 0xee, 0xbd, 0xc0, 0x2d, 0x47, 0xf0, 0x51, 0x0f, 0xf5, 0xdb, 0x43, 0x9f, 0xdc, 0x0c,
	0x4e, 0x4e, 0x2c, 0x1e, 0x6e, 0x5e, 0xfe, 0x3e, 0xac, 0xfd, 0xf8, 0x77, 0xf1, 0x18, 0x8d, 0x2a,
	0x89, 0x37, 0xc4, 0xcd, 0x92, 0xa4, 0xfd, 0x8d, 0x5e, 0xbd, 0xdf, 0x1e, 0xee, 0xae, 0x6b, 0xdf,
	0x42, 0xc2, 0xc3, 0x46, 0xa9, 0x1c, 0x39, 0xaa, 0xf7, 0x15, 0xe1, 0x7d, 0xc5, 0x53, 0xa1, 0x8d,
	0x62, 0x46, 0x80, 0x1c, 0x17, 0x00, 0xd9, 0x38, 0x62, 0x19, 0x93, 0x31, 0xf7, 0xeb, 0xf6, 0xa0,
	0x7d, 0xe2, 0x8a, 0x21, 0x65, 0x31, 0xa4, 0x2a, 0x86, 0x1c, 0x83, 0x90, 0xe1, 0xf3, 0xf2, 0xac,
	0x9f, 0x7f, 0x0e, 0xfb, 0xa9, 0x30, 0x93, 0x4f, 0x11, 0x89, 0x21, 0xa7, 0x55, 0x8b, 0xee, 0xef,
	0xa9, 0x4e, 0x3e, 0x52, 0x73, 0x5e, 0x70, 0x6d, 0x05, 0xda, 0x25, 0xde, 0x5b, 0xb5, 0x3c, 0x01,
	0xc8, 0x42, 0x67, 0xe8, 0x7d, 0x41, 0x78, 0xe7, 0x94, 0xf3, 0x54, 0x31, 0x69, 0xae, 0x47, 0x69,
	0xdc, 0x51, 0x94, 0xed, 0x85, 0xdd, 0x6a, 0x8c, 0xcf, 0xd8, 0x8b, 0x00, 0xf4, 0x8d, 0x08, 0xcd,
	0x3b, 0x8a, 0xd0, 0xb1, 0x5e, 0xab, 0xfe, 0x04, 0x6f, 0x3b, 0x7f, 0xc3, 0x54, 0xca, 0xcd, 0x98,
	0x17, 0x10, 0x4f, 0xb4, 0xdf, 0xea, 0xa1, 0x7e, 0x63, 0xd4, 0xb5, 0xd0, 0x7b, 0x8b, 0xbc, 0xb6,
	0x80, 0x27, 0xb0, 0x9f, 0xf0, 0x8c, 0xa7, 0xee, 0x0a, 0x63, 0x90, 0xa7, 0x42, 0xe5, 0xf6, 0x43,
	0xfb, 0xf7, 0x6c, 0xea, 0xfe, 0xfa, 0x63, 0x78, 0xb5, 0x54, 0x1c, 0xaf, 0x08, 0xaa, 0xe7, 0xb1,
	0x97, 0xdc, 0x8a, 0xea, 0xa3, 0xef, 0x08, 0xef, 0xde, 0xae, 0xf4, 0x9e, 0xe0, 0x6e, 0xa5, 0x02,
	0x35, 0x66, 0x49, 0xa2, 0xb8, 0x76, 0xef, 0x78, 0x73, 0xd4, 0x59, 0x02, 0x2f, 0xdd, 0x7e, 0x49,
	0x9e, 0xb2, 0x4c, 0x24, 0xd7, 0xc8, 0x1b, 0x8e, 0xbc, 0x04, 0x16, 0xe4, 0x47, 0x78, 0x8b, 0x9f,
	0x15, 0x42, 0x9d, 0xbb, 0x26, 0xfc, 0xba, 0x2d, 0xa2, 0xed, 0xf6, 0x6c, 0x07, 0x21, 0xbd, 0x9c,
	0x05, 0xe8, 0x6a, 0x16, 0xa0, 0xbf, 0xb3, 0x00, 0x7d, 0x9b, 0x07, 0xb5, 0xab, 0x79, 0x50, 0xfb,
	0x35, 0x0f, 0x6a, 0x1f, 0x76, 0x96, 0x33, 0x78, 0xe6, 0xa6, 0xd0, 0x5e, 0x40, 0xd4, 0xb2, 0x23,
	0xf8, 0xec, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x07, 0x50, 0x9e, 0x3b, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DelegationConfirmations) > 0 {
		for iNdEx := len(m.DelegationConfirmations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DelegationConfirmations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.BoostTargetEpochs != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.BoostTargetEpochs))
		i--
		dAtA[i] = 0x30
	}
	if len(m.BoostPoolBalance) > 0 {
		for iNdEx := len(m.BoostPoolBalance) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BoostPoolBalance[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.FeegrantPoolBalance) > 0 {
		for iNdEx := len(m.FeegrantPoolBalance) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeegrantPoolBalance[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.RegistrationPoolBalance) > 0 {
		for iNdEx := len(m.RegistrationPoolBalance) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RegistrationPoolBalance[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Nodes) > 0 {
		for iNdEx := len(m.Nodes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Nodes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *DelegationConfirmation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegationConfirmation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegationConfirmation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiryEpoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ExpiryEpoch))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DelegatorAddress) > 0 {
		i -= len(m.DelegatorAddress)
		copy(dAtA[i:], m.DelegatorAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.DelegatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Nodes) > 0 {
		for _, e := range m.Nodes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RegistrationPoolBalance) > 0 {
		for _, e := range m.RegistrationPoolBalance {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.FeegrantPoolBalance) > 0 {
		for _, e := range m.FeegrantPoolBalance {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BoostPoolBalance) > 0 {
		for _, e := range m.BoostPoolBalance {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.BoostTargetEpochs != 0 {
		n += 1 + sovGenesis(uint64(m.BoostTargetEpochs))
	}
	if len(m.DelegationConfirmations) > 0 {
		for _, e := range m.DelegationConfirmations {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *DelegationConfirmation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DelegatorAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.ExpiryEpoch != 0 {
		n += 1 + sovGenesis(uint64(m.ExpiryEpoch))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nodes = append(m.Nodes, Node{})
			if err := m.Nodes[len(m.Nodes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationPoolBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegistrationPoolBalance = append(m.RegistrationPoolBalance, types.Coin{})
			if err := m.RegistrationPoolBalance[len(m.RegistrationPoolBalance)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeegrantPoolBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeegrantPoolBalance = append(m.FeegrantPoolBalance, types.Coin{})
			if err := m.FeegrantPoolBalance[len(m.FeegrantPoolBalance)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BoostPoolBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BoostPoolBalance = append(m.BoostPoolBalance, types.Coin{})
			if err := m.BoostPoolBalance[len(m.BoostPoolBalance)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BoostTargetEpochs", wireType)
			}
			m.BoostTargetEpochs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BoostTargetEpochs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationConfirmations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegationConfirmations = append(m.DelegationConfirmations, DelegationConfirmation{})
			if err := m.DelegationConfirmations[len(m.DelegationConfirmations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DelegationConfirmation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegationConfirmation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegationConfirmation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryEpoch", wireType)
			}
			m.ExpiryEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiryEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
