// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: seocheon/node/v1/genesis.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the x/node module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// nodes is the list of registered nodes at genesis.
	Nodes []Node `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes"`
	// registration_pool_balance is the initial balance for the Registration Pool.
	RegistrationPoolBalance github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=registration_pool_balance,json=registrationPoolBalance,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"registration_pool_balance"`
	// feegrant_pool_balance is the initial balance for the Feegrant Pool.
	FeegrantPoolBalance github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,4,rep,name=feegrant_pool_balance,json=feegrantPoolBalance,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"feegrant_pool_balance"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f54ac42f9ebc09, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetNodes() []Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *GenesisState) GetRegistrationPoolBalance() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.RegistrationPoolBalance
	}
	return nil
}

func (m *GenesisState) GetFeegrantPoolBalance() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.FeegrantPoolBalance
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "seocheon.node.v1.GenesisState")
}

func init() { proto.RegisterFile("seocheon/node/v1/genesis.proto", fileDescriptor_22f54ac42f9ebc09) }

var fileDescriptor_22f54ac42f9ebc09 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x51, 0x3f, 0x4f, 0xfa, 0x40,
	0x18, 0xee, 0xfd, 0xe0, 0x47, 0x62, 0x71, 0xd0, 0x2a, 0x5a, 0x30, 0x1e, 0xc4, 0x89, 0x98, 0x78,
	0x17, 0x30, 0x4e, 0x6e, 0x75, 0x70, 0x33, 0x04, 0x37, 0x17, 0x72, 0x2d, 0x67, 0x69, 0xa4, 0xf7,
	0x36, 0xbd, 0x93, 0xe8, 0xee, 0xe8, 0xe0, 0xe2, 0x77, 0x30, 0x4e, 0x7e, 0x0c, 0x46, 0x46, 0x27,
	0x35, 0x30, 0xf8, 0x35, 0x4c, 0xef, 0x8a, 0x41, 0x99, 0x5d, 0xda, 0x37, 0xf7, 0xbc, 0xcf, 0x9f,
	0x3c, 0xaf, 0x8d, 0x25, 0x87, 0x60, 0xc0, 0x41, 0x50, 0x01, 0x7d, 0x4e, 0x47, 0x2d, 0x1a, 0x72,
	0xc1, 0x65, 0x24, 0x49, 0x92, 0x82, 0x02, 0x67, 0x6d, 0x8e, 0x93, 0x0c, 0x27, 0xa3, 0x56, 0x6d,
	0x9d, 0xc5, 0x91, 0x00, 0xaa, 0xbf, 0x66, 0xa9, 0x86, 0x03, 0x90, 0x31, 0x48, 0xea, 0x33, 0x99,
	0x49, 0xf8, 0x5c, 0xb1, 0x16, 0x0d, 0x20, 0x12, 0x39, 0xbe, 0x19, 0x42, 0x08, 0x7a, 0xa4, 0xd9,
	0x94, 0xbf, 0xee, 0x2c, 0x59, 0x6b, 0x0b, 0x03, 0xee, 0x2e, 0x81, 0x09, 0x4b, 0x59, 0x9c, 0xc7,
	0xda, 0x7b, 0x2c, 0xd8, 0xab, 0xa7, 0x26, 0xe8, 0xb9, 0x62, 0x8a, 0x3b, 0xc7, 0x76, 0xc9, 0x2c,
	0xb8, 0xa8, 0x81, 0x9a, 0xe5, 0xb6, 0x4b, 0x7e, 0x07, 0x27, 0x1d, 0x8d, 0x7b, 0x2b, 0xe3, 0xb7,
	0xba, 0xf5, 0xf4, 0xf9, 0xb2, 0x8f, 0xba, 0x39, 0xc5, 0x69, 0xdb, 0xff, 0xb3, 0x25, 0xe9, 0xfe,
	0x6b, 0x14, 0x9a, 0xe5, 0xf6, 0xd6, 0x32, 0xf7, 0x0c, 0xfa, 0xdc, 0x2b, 0x66, 0xcc, 0xae, 0x59,
	0x75, 0xee, 0x91, 0x5d, 0x4d, 0x79, 0x18, 0x49, 0x95, 0x32, 0x15, 0x81, 0xe8, 0x25, 0x00, 0xc3,
	0x9e, 0xcf, 0x86, 0x4c, 0x04, 0xdc, 0x2d, 0x68, 0xa1, 0x2a, 0x31, 0xc5, 0x90, 0xac, 0x18, 0x92,
	0x17, 0x43, 0x4e, 0x20, 0x12, 0xde, 0x51, 0xa6, 0xf5, 0xfc, 0x5e, 0x6f, 0x86, 0x91, 0x1a, 0x5c,
	0xfb, 0x24, 0x80, 0x98, 0xe6, 0x2d, 0x9a, 0xdf, 0x81, 0xec, 0x5f, 0x51, 0x75, 0x9b, 0x70, 0xa9,
	0x09, 0xd2, 0x24, 0xde, 0x5e, 0xb4, 0xec, 0x00, 0x0c, 0x3d, 0x63, 0xe8, 0xdc, 0x21, 0xbb, 0x72,
	0xc9, 0x79, 0x98, 0x32, 0xa1, 0x7e, 0x46, 0x29, 0xfe, 0x51, 0x94, 0x8d, 0xb9, 0xdd, 0x42, 0x0c,
	0x8f, 0x8e, 0xa7, 0x18, 0x4d, 0xa6, 0x18, 0x7d, 0x4c, 0x31, 0x7a, 0x98, 0x61, 0x6b, 0x32, 0xc3,
	0xd6, 0xeb, 0x0c, 0x5b, 0x17, 0x95, 0xef, 0x83, 0xde, 0x98, 0x93, 0x6a, 0x41, 0xbf, 0xa4, 0xef,
	0x79, 0xf8, 0x15, 0x00, 0x00, 0xff, 0xff, 0x66, 0xd0, 0x04, 0xa6, 0x88, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FeegrantPoolBalance) > 0 {
		for iNdEx := len(m.FeegrantPoolBalance) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeegrantPoolBalance[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.RegistrationPoolBalance) > 0 {
		for iNdEx := len(m.RegistrationPoolBalance) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RegistrationPoolBalance[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Nodes) > 0 {
		for iNdEx := len(m.Nodes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Nodes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Nodes) > 0 {
		for _, e := range m.Nodes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RegistrationPoolBalance) > 0 {
		for _, e := range m.RegistrationPoolBalance {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.FeegrantPoolBalance) > 0 {
		for _, e := range m.FeegrantPoolBalance {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nodes = append(m.Nodes, Node{})
			if err := m.Nodes[len(m.Nodes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationPoolBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegistrationPoolBalance = append(m.RegistrationPoolBalance, types.Coin{})
			if err := m.RegistrationPoolBalance[len(m.RegistrationPoolBalance)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeegrantPoolBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeegrantPoolBalance = append(m.FeegrantPoolBalance, types.Coin{})
			if err := m.FeegrantPoolBalance[len(m.FeegrantPoolBalance)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
