// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: seocheon/node/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the x/node module.
type Params struct {
	// max_registrations_per_block is the maximum number of node registrations per block.
	MaxRegistrationsPerBlock uint64 `protobuf:"varint,1,opt,name=max_registrations_per_block,json=maxRegistrationsPerBlock,proto3" json:"max_registrations_per_block,omitempty"`
	// registration_cooldown_blocks is the cooldown period (in blocks) before same operator can re-register.
	RegistrationCooldownBlocks uint64 `protobuf:"varint,2,opt,name=registration_cooldown_blocks,json=registrationCooldownBlocks,proto3" json:"registration_cooldown_blocks,omitempty"`
	// registration_deposit is the optional deposit required for registration (in uppyeo). Initially 0.
	RegistrationDeposit cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=registration_deposit,json=registrationDeposit,proto3,customtype=cosmossdk.io/math.Int" json:"registration_deposit"`
	// agent_allowed_msg_types is the whitelist of message types that agent_address can execute.
	AgentAllowedMsgTypes []string `protobuf:"bytes,4,rep,name=agent_allowed_msg_types,json=agentAllowedMsgTypes,proto3" json:"agent_allowed_msg_types,omitempty"`
	// agent_address_change_cooldown is the cooldown period (in blocks) between agent address changes.
	AgentAddressChangeCooldown uint64 `protobuf:"varint,5,opt,name=agent_address_change_cooldown,json=agentAddressChangeCooldown,proto3" json:"agent_address_change_cooldown,omitempty"`
	// agent_feegrant_allowed_msg_types is the whitelist of message types allowed for feegrant usage.
	// This is a subset of agent_allowed_msg_types, excluding MsgSend to prevent feegrant fund drain.
	AgentFeegrantAllowedMsgTypes []string `protobuf:"bytes,8,rep,name=agent_feegrant_allowed_msg_types,json=agentFeegrantAllowedMsgTypes,proto3" json:"agent_feegrant_allowed_msg_types,omitempty"`
	// max_tags is the maximum number of tags per node.
	MaxTags uint32 `protobuf:"varint,6,opt,name=max_tags,json=maxTags,proto3" json:"max_tags,omitempty"`
	// max_tag_length is the maximum character length of each tag.
	MaxTagLength uint32 `protobuf:"varint,7,opt,name=max_tag_length,json=maxTagLength,proto3" json:"max_tag_length,omitempty"`
	// delegation_confirmation_period is the number of epochs between required delegation confirmations.
	// Default: 90 (~3 months). 0 disables active delegation.
	DelegationConfirmationPeriod uint64 `protobuf:"varint,9,opt,name=delegation_confirmation_period,json=delegationConfirmationPeriod,proto3" json:"delegation_confirmation_period,omitempty"`
	// delegation_renewal_window is the number of epochs at the end of a confirmation period
	// during which MsgConfirmDelegation is accepted. Must be less than delegation_confirmation_period.
	// Default: 7 (~7 days).
	DelegationRenewalWindow uint64 `protobuf:"varint,10,opt,name=delegation_renewal_window,json=delegationRenewalWindow,proto3" json:"delegation_renewal_window,omitempty"`
	// epoch_length is the number of blocks per epoch. Default: 17280 (~1 day).
	// Governs agent_share scheduling, delegation confirmation epochs, and boost distribution.
	EpochLength int64 `protobuf:"varint,11,opt,name=epoch_length,json=epochLength,proto3" json:"epoch_length,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_866ab82813f4e28b, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxRegistrationsPerBlock() uint64 {
	if m != nil {
		return m.MaxRegistrationsPerBlock
	}
	return 0
}

func (m *Params) GetRegistrationCooldownBlocks() uint64 {
	if m != nil {
		return m.RegistrationCooldownBlocks
	}
	return 0
}

func (m *Params) GetAgentAllowedMsgTypes() []string {
	if m != nil {
		return m.AgentAllowedMsgTypes
	}
	return nil
}

func (m *Params) GetAgentAddressChangeCooldown() uint64 {
	if m != nil {
		return m.AgentAddressChangeCooldown
	}
	return 0
}

func (m *Params) GetAgentFeegrantAllowedMsgTypes() []string {
	if m != nil {
		return m.AgentFeegrantAllowedMsgTypes
	}
	return nil
}

func (m *Params) GetMaxTags() uint32 {
	if m != nil {
		return m.MaxTags
	}
	return 0
}

func (m *Params) GetMaxTagLength() uint32 {
	if m != nil {
		return m.MaxTagLength
	}
	return 0
}

func (m *Params) GetDelegationConfirmationPeriod() uint64 {
	if m != nil {
		return m.DelegationConfirmationPeriod
	}
	return 0
}

func (m *Params) GetDelegationRenewalWindow() uint64 {
	if m != nil {
		return m.DelegationRenewalWindow
	}
	return 0
}

func (m *Params) GetEpochLength() int64 {
	if m != nil {
		return m.EpochLength
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "seocheon.node.v1.Params")
}

func init() { proto.RegisterFile("seocheon/node/v1/params.proto", fileDescriptor_866ab82813f4e28b) }

var fileDescriptor_866ab82813f4e28b = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0xb3, 0xb6, 0x4d, 0x9b, 0x41, 0x45, 0xd7, 0xd4, 0x4e, 0x63, 0xb2, 0x09, 0xe2, 0x21,
	0x78, 0xc8, 0x52, 0xc4, 0x4b, 0x41, 0xb0, 0x49, 0x29, 0x08, 0x0a, 0x61, 0x29, 0x08, 0x5e, 0x86,
	0x69, 0xe6, 0x75, 0xb2, 0x74, 0x77, 0xde, 0x32, 0x33, 0x34, 0xf1, 0xe8, 0xd5, 0x93, 0x1f, 0xc1,
	0x8f, 0xe0, 0xc7, 0xe8, 0xb1, 0x47, 0xf1, 0x50, 0x24, 0x39, 0xe8, 0xc7, 0x90, 0xcc, 0x24, 0xed,
	0x5a, 0x7a, 0x59, 0x66, 0xe7, 0xff, 0xfb, 0xff, 0x79, 0x6f, 0xde, 0x23, 0x2d, 0x03, 0x38, 0x1a,
	0x03, 0xaa, 0x58, 0xa1, 0x80, 0xf8, 0x7c, 0x2f, 0x2e, 0xb8, 0xe6, 0xb9, 0xe9, 0x15, 0x1a, 0x2d,
	0x86, 0x8f, 0x56, 0x72, 0x6f, 0x21, 0xf7, 0xce, 0xf7, 0x1a, 0x8f, 0x79, 0x9e, 0x2a, 0x8c, 0xdd,
	0xd7, 0x43, 0x8d, 0xba, 0x44, 0x89, 0xee, 0x18, 0x2f, 0x4e, 0xfe, 0xf6, 0xf9, 0x97, 0x0d, 0x52,
	0x1d, 0xba, 0xac, 0xf0, 0x0d, 0x79, 0x96, 0xf3, 0x29, 0xd3, 0x20, 0x53, 0x63, 0x35, 0xb7, 0x29,
	0x2a, 0xc3, 0x0a, 0xd0, 0xec, 0x24, 0xc3, 0xd1, 0x19, 0x0d, 0x3a, 0x41, 0x77, 0x3d, 0xa1, 0x39,
	0x9f, 0x26, 0x65, 0x62, 0x08, 0xba, 0xbf, 0xd0, 0xc3, 0xb7, 0xa4, 0x59, 0xb6, 0xb2, 0x11, 0x62,
	0x26, 0x70, 0xa2, 0xbc, 0xdd, 0xd0, 0x7b, 0xce, 0xdf, 0x28, 0x33, 0x83, 0x25, 0xe2, 0x02, 0x4c,
	0x38, 0x24, 0xf5, 0xff, 0x12, 0x04, 0x14, 0x68, 0x52, 0x4b, 0xd7, 0x3a, 0x41, 0xb7, 0xd6, 0x6f,
	0x5d, 0x5c, 0xb5, 0x2b, 0xbf, 0xae, 0xda, 0xdb, 0x23, 0x34, 0x39, 0x1a, 0x23, 0xce, 0x7a, 0x29,
	0xc6, 0x39, 0xb7, 0xe3, 0xde, 0x3b, 0x65, 0x93, 0x27, 0x65, 0xeb, 0xa1, 0x77, 0x86, 0xaf, 0xc9,
	0x0e, 0x97, 0xa0, 0x2c, 0xe3, 0x59, 0x86, 0x13, 0x10, 0x2c, 0x37, 0x92, 0xd9, 0xcf, 0x05, 0x18,
	0xba, 0xde, 0x59, 0xeb, 0xd6, 0x92, 0xba, 0x93, 0x0f, 0xbc, 0xfa, 0xc1, 0xc8, 0xe3, 0x85, 0x16,
	0x1e, 0x90, 0xd6, 0xd2, 0x26, 0x84, 0x06, 0x63, 0xd8, 0x68, 0xcc, 0x95, 0x84, 0xeb, 0x96, 0xe8,
	0x86, 0xef, 0xc5, 0x9b, 0x3d, 0x33, 0x70, 0xc8, 0xaa, 0xa3, 0xf0, 0x88, 0x74, 0x7c, 0xc4, 0x29,
	0x80, 0xd4, 0xfc, 0xce, 0x12, 0xb6, 0x5c, 0x09, 0x4d, 0xc7, 0x1d, 0x2d, 0xb1, 0xdb, 0xa5, 0xec,
	0x92, 0xad, 0xc5, 0x50, 0x2c, 0x97, 0x86, 0x56, 0x3b, 0x41, 0xf7, 0x41, 0xb2, 0x99, 0xf3, 0xe9,
	0x31, 0x97, 0x26, 0x7c, 0x41, 0x1e, 0x2e, 0x25, 0x96, 0x81, 0x92, 0x76, 0x4c, 0x37, 0x1d, 0x70,
	0xdf, 0x03, 0xef, 0xdd, 0x5d, 0x78, 0x48, 0x22, 0x01, 0x19, 0xc8, 0xd5, 0x50, 0xd4, 0x69, 0xaa,
	0x73, 0xff, 0x53, 0x80, 0x4e, 0x51, 0xd0, 0x9a, 0x6b, 0xa6, 0x79, 0x43, 0x0d, 0x4a, 0xd0, 0xd0,
	0x31, 0xe1, 0x3e, 0xd9, 0x2d, 0xa5, 0x68, 0x50, 0x30, 0xe1, 0x19, 0x9b, 0xa4, 0x4a, 0xe0, 0x84,
	0x12, 0x17, 0xb0, 0x73, 0x03, 0x24, 0x5e, 0xff, 0xe8, 0xe4, 0xfd, 0xf6, 0xdf, 0xef, 0xed, 0xe0,
	0xeb, 0x9f, 0x1f, 0x2f, 0x9f, 0x5e, 0x6f, 0xf1, 0xd4, 0xef, 0xb1, 0x5f, 0xbc, 0x7e, 0x7c, 0x31,
	0x8b, 0x82, 0xcb, 0x59, 0x14, 0xfc, 0x9e, 0x45, 0xc1, 0xb7, 0x79, 0x54, 0xb9, 0x9c, 0x47, 0x95,
	0x9f, 0xf3, 0xa8, 0xf2, 0x69, 0xfb, 0xb6, 0xc3, 0x3d, 0xdc, 0x49, 0xd5, 0xed, 0xee, 0xab, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x9e, 0x14, 0x8e, 0x17, 0x03, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MaxRegistrationsPerBlock != that1.MaxRegistrationsPerBlock {
		return false
	}
	if this.RegistrationCooldownBlocks != that1.RegistrationCooldownBlocks {
		return false
	}
	if !this.RegistrationDeposit.Equal(that1.RegistrationDeposit) {
		return false
	}
	if len(this.AgentAllowedMsgTypes) != len(that1.AgentAllowedMsgTypes) {
		return false
	}
	for i := range this.AgentAllowedMsgTypes {
		if this.AgentAllowedMsgTypes[i] != that1.AgentAllowedMsgTypes[i] {
			return false
		}
	}
	if this.AgentAddressChangeCooldown != that1.AgentAddressChangeCooldown {
		return false
	}
	if len(this.AgentFeegrantAllowedMsgTypes) != len(that1.AgentFeegrantAllowedMsgTypes) {
		return false
	}
	for i := range this.AgentFeegrantAllowedMsgTypes {
		if this.AgentFeegrantAllowedMsgTypes[i] != that1.AgentFeegrantAllowedMsgTypes[i] {
			return false
		}
	}
	if this.MaxTags != that1.MaxTags {
		return false
	}
	if this.MaxTagLength != that1.MaxTagLength {
		return false
	}
	if this.DelegationConfirmationPeriod != that1.DelegationConfirmationPeriod {
		return false
	}
	if this.DelegationRenewalWindow != that1.DelegationRenewalWindow {
		return false
	}
	if this.EpochLength != that1.EpochLength {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EpochLength != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EpochLength))
		i--
		dAtA[i] = 0x58
	}
	if m.DelegationRenewalWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DelegationRenewalWindow))
		i--
		dAtA[i] = 0x50
	}
	if m.DelegationConfirmationPeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DelegationConfirmationPeriod))
		i--
		dAtA[i] = 0x48
	}
	if len(m.AgentFeegrantAllowedMsgTypes) > 0 {
		for iNdEx := len(m.AgentFeegrantAllowedMsgTypes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AgentFeegrantAllowedMsgTypes[iNdEx])
			copy(dAtA[i:], m.AgentFeegrantAllowedMsgTypes[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.AgentFeegrantAllowedMsgTypes[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if m.MaxTagLength != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxTagLength))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxTags != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxTags))
		i--
		dAtA[i] = 0x30
	}
	if m.AgentAddressChangeCooldown != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AgentAddressChangeCooldown))
		i--
		dAtA[i] = 0x28
	}
	if len(m.AgentAllowedMsgTypes) > 0 {
		for iNdEx := len(m.AgentAllowedMsgTypes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AgentAllowedMsgTypes[iNdEx])
			copy(dAtA[i:], m.AgentAllowedMsgTypes[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.AgentAllowedMsgTypes[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size := m.RegistrationDeposit.Size()
		i -= size
		if _, err := m.RegistrationDeposit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.RegistrationCooldownBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RegistrationCooldownBlocks))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxRegistrationsPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxRegistrationsPerBlock))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxRegistrationsPerBlock != 0 {
		n += 1 + sovParams(uint64(m.MaxRegistrationsPerBlock))
	}
	if m.RegistrationCooldownBlocks != 0 {
		n += 1 + sovParams(uint64(m.RegistrationCooldownBlocks))
	}
	l = m.RegistrationDeposit.Size()
	n += 1 + l + sovParams(uint64(l))
	if len(m.AgentAllowedMsgTypes) > 0 {
		for _, s := range m.AgentAllowedMsgTypes {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.AgentAddressChangeCooldown != 0 {
		n += 1 + sovParams(uint64(m.AgentAddressChangeCooldown))
	}
	if m.MaxTags != 0 {
		n += 1 + sovParams(uint64(m.MaxTags))
	}
	if m.MaxTagLength != 0 {
		n += 1 + sovParams(uint64(m.MaxTagLength))
	}
	if len(m.AgentFeegrantAllowedMsgTypes) > 0 {
		for _, s := range m.AgentFeegrantAllowedMsgTypes {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.DelegationConfirmationPeriod != 0 {
		n += 1 + sovParams(uint64(m.DelegationConfirmationPeriod))
	}
	if m.DelegationRenewalWindow != 0 {
		n += 1 + sovParams(uint64(m.DelegationRenewalWindow))
	}
	if m.EpochLength != 0 {
		n += 1 + sovParams(uint64(m.EpochLength))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRegistrationsPerBlock", wireType)
			}
			m.MaxRegistrationsPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRegistrationsPerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationCooldownBlocks", wireType)
			}
			m.RegistrationCooldownBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistrationCooldownBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationDeposit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RegistrationDeposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentAllowedMsgTypes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentAllowedMsgTypes = append(m.AgentAllowedMsgTypes, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentAddressChangeCooldown", wireType)
			}
			m.AgentAddressChangeCooldown = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AgentAddressChangeCooldown |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTags", wireType)
			}
			m.MaxTags = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTags |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTagLength", wireType)
			}
			m.MaxTagLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTagLength |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentFeegrantAllowedMsgTypes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentFeegrantAllowedMsgTypes = append(m.AgentFeegrantAllowedMsgTypes, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationConfirmationPeriod", wireType)
			}
			m.DelegationConfirmationPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DelegationConfirmationPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationRenewalWindow", wireType)
			}
			m.DelegationRenewalWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DelegationRenewalWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochLength", wireType)
			}
			m.EpochLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochLength |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
